Kanto = {
    "Route 1": ["Pidgey", "Rattata", "Oddish", "Bellsprout", "Hoothoot", "Sentret", "Poochyena", "Ledyba", "Spinarak", "Pineco", "Wurmple"], 
    "Route 2": ["Pidgey", "Rattata", "Oddish", "Bellsprout", "Caterpie", "Weedle", "Hoothoot", "Ledyba", "Spinarak", "Pineco", "Wurmple", "Mime Jr.", "Pichu", "Nidoran M", "Nidoran F"], 
    "Route 3": ["Rattata", "Spearow", "Ekans", "Sandshrew", "Mankey", "Charmander", "Zubat", "Igglybuff", "Gulpin", "Baltoy", "Hoothoot", "Pineco", "Wurmple", "Pidgey", "Nidoran M", "Nidoran F", "Cleffa"], 
    "Route 4": ["Spearow", "Rattata", "Ekans", "Sandshrew", "Mankey", "Psyduck", "Charmander", "Tentacool", "Magikarp", "Zubat", "Igglybuff", "Krabby", "Horsea", "Slowpoke", "Cleffa", "Goldeen"], 
    "Route 5": ["Rattata", "Pidgey", "Vulpix", "Growlithe", "Igglybuff", "Abra", "Happiny", "Oddish", "Meowth", "Bellsprout", "Hoothoot", "Pineco", "Combee", "Nidoran M", "Snubbull", "Mankey", "Machop", "Nidoran F"], 
    "Route 6": ["Pidgey", "Rattata", "Vulpix", "Growlithe", "Igglybuff", "Psyduck", "Abra", "Happiny", "Goldeen", "Magikarp", "Oddish", "Meowth", "Bellsprout", "Magnemite", "Poliwag", "Hoothoot", "Pineco", "Combee", "Slowpoke", "Drowzee", "Snubbull", "Shellder", "Krabby"], 
    "Route 7": ["Vulpix", "Growlithe", "Pidgey", "Rattata", "Igglybuff", "Abra", "Porygon", "Spearow", "Meowth", "Murkrow", "Houndour", "Heracross", "Combee", "Oddish", "Bellsprout", "Snubbull", "Mankey"],
    "Route 8": ["Vulpix", "Growlithe", "Pidgey", "Rattata", "Igglybuff", "Abra", "Happiny", "Meowth", "Gastly", "Hoothoot", "Pineco", "Combee", "Ekans", "Sandshrew", "Snubbull", "Mankey"],
    "Route 9": ["Rattata", "Spearow", "Nidoran M", "Happiny", "Mankey", "Sableye", "Mawile", "Goldeen", "Magikarp", "Ekans", "Sandshrew", "Venonat", "Zubat", "Cubone", "Nidoran F"],
    "Route 10": ["Rattata", "Spearow", "Nidoran M", "Krabby", "Happiny", "Tentacool", "Magikarp", "Dratini", "Voltorb", "Wooper", "Elekid", "Goldeen", "Zapdos", "Ekans", "Sandshrew", "Horsea", "Psyduck", "Slowpoke", "Venonat", "Zubat", "Cubone", "Magnemite", "Machop", "Poliwag", "Nidoran F"],
    "Route 11": ["Pidgey", "Rattata", "Drowzee", "Mime Jr.", "Happiny", "Tentacool", "Horsea", "Magikarp", "Magnemite", "Munchlax", "Spearow", "Heracross", "Combee", "Ekans", "Sandshrew", "Psyduck", "Krabby", "Slowpoke", "Nidoran M", "Meowth", "Hoppip", "Hoothoot", "Shellder", "Poliwag", "Diglett", "Goldeen", "Nidoran F"],
    "Route 12": ["Pidgey", "Oddish", "Bellsprout", "Krabby", "Farfetch'd", "Happiny", "Tentacool", "Horsea", "Magikarp", "Munchlax", "Relicanth", "Wooper", "Qwilfish", "Hoothoot", "Ledyba", "Spinarak", "Wurmple", "Venonat", "Psyduck", "Slowpoke", "Goldeen", "Poliwag"],
    "Route 13": ["Pidgey", "Oddish", "Bellsprout", "Krabby", "Farfetch'd", "Happiny", "Tentacool", "Horsea", "Magikarp", "Nidoran M", "Hoothoot", "Hoppip", "Wooper", "Qwilfish", "Ledyba", "Spinarak", "Wurmple", "Venonat", "Ditto", "Psyduck", "Slowpoke", "Goldeen", "Poliwag", "Nidoran F"],
    "Route 14": ["Pidgey", "Oddish", "Venonat", "Bellsprout", "Tauros", "Scyther", "Pinsir", "Happiny", "Nidoran M", "Hoppip", "Hoothoot", "Wooper", "Ledyba", "Spinarak", "Wurmple", "Ditto", "Aerodactyl", "Nidoran F"],
    "Route 15": ["Pidgey", "Oddish", "Bellsprout", "Venonat", "Tauros", "Scyther", "Pinsir", "Happiny", "Nidoran M", "Hoothoot", "Hoppip", "Wooper", "Ledyba", "Spinarak", "Wurmple", "Ditto", "Nidoran F"],
    "Route 16": ["Doduo", "Pidgey", "Rattata", "Happiny", "Munchlax", "Spearow", "Grimer", "Slugma", "Murkrow", "Heracross", "Combee"],
    "Route 17": ["Ponyta", "Doduo", "Psyduck", "Pidgey", "Rattata", "Eevee", "Happiny", "Spearow", "Grimer", "Slugma", "Tentacool", "Krabby", "Goldeen", "Magikarp", "Shellder", "Poliwag"],
    "Route 18": ["Pidgey", "Doduo", "Rattata", "Happiny", "Tentacool", "Staryu", "Magikarp", "Spearow", "Grimer", "Slugma", "Hoothoot", "Ledyba", "Spinarak", "Wurmple", "Lickitung", "Murkrow", "Krabby", "Goldeen", "Shellder", "Poliwag", "Paras"],
    "Route 19": ["Tentacool", "Staryu", "Magikarp", "Lapras", "Clamperl", "Krabby", "Horsea", "Psyduck", "Slowpoke", "Corsola", "Goldeen", "Shellder", "Poliwag"],
    "Route 20": ["Lapras", "Tentacool", "Magikarp", "Shellder", "Chinchou", "Krabby", "Horsea", "Psyduck", "Slowpoke", "Staryu", "Corsola", "Goldeen", "Poliwag"],
    "Route 21": ["Pidgey", "Rattata", "Tangela", "Oddish", "Bellsprout", "Happiny", "Tentacool", "Staryu", "Magikarp", "Mime Jr.", "Shellder", "Chinchou", "Hoothoot", "Ledyba", "Spinarak", "Wurmple", "Krabby", "Horsea", "Psyduck", "Slowpoke", "Corsola", "Goldeen", "Poliwag"],
    "Route 22": ["Rattata", "Spearow", "Nidoran M", "Nidoran F", "Poliwag", "Magikarp", "Ponyta", "Doduo", "Hoothoot", "Ledyba", "Spinarak", "Pineco", "Wurmple", "Mankey", "Psyduck", "Slowpoke", "Goldeen"],
    "Route 23": ["Nidoran M", "Nidoran F", "Spearow", "Exeggcute", "Happiny", "Poliwag", "Magikarp", "Mankey", "Ekans", "Sandshrew", "Psyduck", "Slowpoke", "Goldeen", "Ditto", "Krabby", "Horsea"],
    "Route 24": ["Pidgey", "Venonat", "Oddish", "Bellsprout", "Meowth", "Psyduck", "Squirtle", "Tentacool", "Magikarp", "Charmander", "Sunkern", "Abra", "Goldeen", "Caterpie", "Weedle", "Krabby", "Horsea", "Slowpoke", "Horsea", "Poliwag"],
    "Route 25": ["Pidgey", "Venonat", "Oddish", "Bellsprout", "Meowth", "Psyduck", "Squirtle", "Poliwag", "Magikarp", "Abra", "Buneary", "Goldeen", "Suicune", "Hoothoot", "Combee", "Slakoth", "Caterpie", "Weedle", "Slowpoke", "Krabby"],
    "Route 26": ["Rattata", "Sandshrew", "Ekans", "Doduo", "Ponyta", "Wooper", "Tentacool", "Shellder", "Chinchou", "Magikarp", "Exeggcute", "Hoothoot", "Ledyba", "Spinarak", "Pineco", "Caterpie", "Weedle"],
    "Route 27": ["Rattata", "Ekans", "Doduo", "Wooper", "Sandshrew", "Ponyta", "Tentacool", "Luvdisc", "Shellder", "Chinchou", "Magikarp", "Exeggcute", "Hoothoot", "Ledyba", "Spinarak", "Pineco", "Caterpie", "Weedle"],
    "Route 28": ["Ponyta", "Tangela", "Doduo", "Sneasel", "Teddiursa", "Phanpy", "Poliwag", "Magikarp", "Natu", "Aipom", "Heracross", "Zubat", "Ekans"],
    "Berry Forest": ["Venonat", "Psyduck", "Slowpoke", "Drowzee", "Exeggucte", "Pidgey", "Oddish", "Bellsprout", "Goldeen", "Magikarp", "Poliwag"],
    "Bond Bridge": ["Pidgey", "Venonat", "Meowth", "Psyduck", "Slowpoke", "Oddish", "Bellsprout", "Tentacool", "Krabby", "Horsea", "Magikarp"],
    "Canyon Entrance": ["Sentret", "Meowth", "Psyduck", "Slopwoke", "Spearow", "Phanpy"],
    "Cape Brink": ["Oddish", "Bellsprout", "Meowth", "Psyduck", "Slowpoke", "Spearow", "Poliwag", "Magikarp", "Goldeen"],
    "Celadon City": ["Eevee", "Vulpix (A)", "Sandshrew (A)", "Grimer", "Heracross", "Combee", "Mime Jr.", "Porygon", "Psyduck", "Slowpoke", "Koffing", "Magikarp", "Cleffa", "Abra", "Scyther", "Pinsir", "Dratini", "Pichu", "Larvitar", "Poliwag", "Goldeen", "Nidoran M", "Nidoran F", "Vulpix", "Igglybuff"],
    "Cerulean Cave": ["Zubat", "Psyduck", "Geodude", "Lickitung", "Rhyhorn", "Ditto", "Munchlax", "Poliwag", "Magikarp", "Happiny", "Mewtwo", "Meowth", "Mankey", "Machop", "Voltorb", "Wynaut", "Paras", "Magnemite", "Goldeen", "Abra", "Slowpoke", "Drowzee", "Ekans", "Sandshrew", "Venonat", "Doduo", "Oddish", "Bellsprout", "Pichu", "Krabby", "Horsea", "Cubone", "Igglybuff"],
    "Cerulean City": ["Bulbasaur", "Rattata (A)", "Goldeen", "Magikarp", "Hoothoot", "Pineco", "Combee", "Tentacool", "Krabby", "Horsea", "Psyduck", "Slowpoke", "Smoochum"],
    "Cinnabar Island": ["Omanyte", "Kabuto", "Aerodactyl", "Meowth (A)", "Grimer (A)", "Tentacool", "Shellder", "Chinchou", "Magikarp", "Krabby", "Horsea", "Staryu", "Psyduck", "Slowpoke", "Seel", "Voltorb", "Tangela", "Grimer", "Rhyhorn"],
    "Digglet's Cave": ["Diglett", "Zubat", "Happiny", "Rhyhorn"],
    "Five Island": ["Tentacool", "Hoppip", "Shellder", "Krabby", "Horsea", "Staryu", "Psyduck", "Slowpoke", "Magikarp"],
    "Five Isle Meadow": ["Sentret", "Meowth", "Psyduck", "Slowpoke", "Pidgey", "Hoppip", "Tentacool", "Krabby", "Horsea", "Qwilfish", "Remoraid", "Magikarp"],
    "Four Island": ["Psyduck", "Slowpoke", "Azurill", "Wooper", "Poliwag", "Magikarp", "Goldeen"],
    "Fuchsia City": ["Cubone", "Magikarp", "Hoothoot", "Ledyba", "Spinarak", "Wurmple", "Psyduck", "Slowpoke", "Goldeen", "Poliwag", "Krabby"],
    "Green Path": ["Tentacool", "Krabby", "Horsea", "Qwilfish", "Remoraid", "Psyduck", "Slowpoke", "Magikarp"],
    "Hoenn Sound": ["Zigzagoon", "Whismur", "Makuhita", "Plusle", "Minun", "Numel", "Spoink", "Absol"],
    "Icefall Cave": ["Zubat", "Seel", "Psyduck", "Slowpoke", "Azurill", "Poliwag", "Magikarp", "Goldeen", "Swinub", "Sneasel", "Delibird", "Tentacool", "Lapras", "Shellder", "Krabby", "Horsea", "Staryu"],
    "Indigo Plateau": ["Exeggutor (A)"],
    "Kindle Road": ["Spearow", "Ponyta", "Meowth", "Psyduck", "Slowpoke", "Geodude", "Tentacool", "Krabby", "Horsea", "Magikarp"],
    "Lavender Town": ["Diglett (A)"],
    "Lost Cave": ["Gastly", "Murkrow", "Misdreavus", "Zubat"],
    "Memorial Pillar": ["Hoppip", "Tentacool", "Krabby", "Horsea", "Qwilfish", "Remoraid", "Psyduck", "Slowpoke", "Magikarp"],
    "Mt. Ember": ["Geodude", "Slugma", "Machop", "Ponyta", "Spearow", "Magby", "Moltres"],
    "Mt. Moon": ["Zubat", "Geodude", "Paras", "Cleffa", "Onix", "Happiny", "Sandshrew", "Poliwag", "Magikarp"],
    "Navel Rock": ["Lugia", "Ho-oh"],
    "One Island": ["Tentacool", "Shellder", "Krabby", "Horsea", "Staryu", "Psyduck", "Slowpoke", "Magikarp"],
    "Outcast Island": ["Tentacool", "Krabby", "Horsea", "Qwilfish", "Remoraid", "Psyduck", "Slowpoke", "Magikarp"],
    "Pallet Town": ["Pichu", "Eevee", "Tentacool", "Shellder", "Chinchou", "Magikarp", "Bulbasaur", "Charmander", "Squirtle", "Hoothoot", "Ledyba", "Spinarak", "Pineco", "Wurmple", "Krabby", "Horsea", "Staryu", "Psyduck", "Slowpoke", "Poliwag", "Goldeen"],
    "Pattern Bush": ["Ledyba", "Spinarak", "Caterpie", "Weedle", "Heracross"],
    "Pewter City": ["Omanyte", "Kabuto", "Aerodactyl", "Lileep", "Anorith", "Cranidos", "Shieldon", "Latios", "Latias", "Hoothoot", "Pineco", "Wurmple", "Starly", "Natu", "Ponyta"],
    "Pokémon Mansion": ["Grimer", "Koffing", "Rattata", "Magby", "Ditto", "Happiny", "Vulpix", "Growlithe", "Ponyta"],
    "Pokémon Tower": ["Gastly", "Cubone", "Zubat", "Happiny"],
    "Power Plant": ["Grimer", "Koffing", "Magnemite", "Voltorb", "Elekid", "Happiny", "Zapdos", "Pichu"],
    "Resort Gorgeous": ["Tentacool", "Hoppip", "Krabby", "Horsea", "Qwilfish", "Remoraid", "Psyduck", "Slowpoke", "Magikarp"],
    "Roaming Kanto": ["Latios", "Latias", "Entei", "Raikou", "Suicune"],
    "Rock Tunnel": ["Zubat", "Geodude", "Machop", "Onix", "Cubone", "Rhyhorn", "Kangaskhan", "Charmander", "Mankey", "Gastly"],
    "Ruin Valley": ["Natu", "Meowth", "Psyduck", "Slowpoke", "Wynaut", "Spearow", "Azurill", "Yanma", "Wooper", "Poliwag", "Magikarp", "Goldeen"],
    "Safari Zone": ["Nidoran M", "Nidoran F", "Exeggcute", "Rhyhorn", "Venonat", "Paras", "Scyther", "Pinsir", "Happiny", "Psyduck", "Slowpoke", "Goldeen", "Dratini", "Poliwag", "Magikarp", "Doduo", "Kangaskhan", "Tauros", "Tangela", "Krabby", "Cubone"],
    "Saffron City": ["Hitmonlee", "Hitmonchan", "Lapras", "Pichu"],
    "Seafoam Islands": ["Zubat", "Slowpoke", "Seel", "Smoochum", "Squirtle", "Tentacool", "Shellder", "Magikarp", "Articuno", "Psyduck", "Horsea", "Krabby", "Staryu", "Goldeen", "Poliwag"],
    "Sevault Canyon": ["Geodude", "Phanpy", "Meowth", "Onix", "Skarmory", "Larvitar", "Spearow", "Cubone"],
    "Sinnoh Sound": ["Bidoof", "Shinx", "Budew", "Buizel", "Chingling", "Bronzor", "Carnivine"],
    "Silph Co.": ["Porygon", "Treecko", "Torchic", "Mudkip", "Beldum", "Lapras"],
    "Sky": ["Pidgey", "Spearow", "Charmander", "Dratini", "Articuno", "Zapdos", "Moltres"],
    "Tanoby Ruins": ["Unown", "Tentacool", "Mantyke", "Krabby", "Horsea", "Qwilfish", "Remoraid", "Psyduck", "Krabby", "Magikarp"],
    "Three Isle Port": ["Dunsparce"],
    "Tohjo Falls": ["Rattata", "Zubat", "Slowpoke", "Goldeen", "Magikarp"],
    "Trainer Tower": ["Tentacool", "Krabby", "Horsea", "Qwilfish", "Remoraid", "Psyduck", "Slowpoke", "Krabby", "Magikarp"],
    "Treasure Beach": ["Spearow", "Tangela", "Meowth", "Psyduck", "Slowpoke", "Tentacool", "Krabby", "Horsea", "Psyduck", "Slowpoke", "Magikarp"],
    "Underground Path 5-6": ["Nidoran M", "Nidoran F", "Machop"],
    "Vermillion City": ["Squirtle", "Meowth", "Growlithe", "Geodude (A)", "Tentacool", "Wingull", "Shellder", "Chinchou", "Magikarp", "Spearow", "Heracross", "Combee", "Diglett", "Shuckle", "Krabby", "Horsea", "Staryu", "Psyduck", "Slowpoke", "Farfetch'd", "Munchlax", "Goldeen", "Poliwag"],
    "Victory Road": ["Zubat", "Machop", "Geodude", "Onix", "Rhyhorn", "Hitmonlee", "Hitmonchan", "Happiny", "Moltres", "Teddiursa", "Phanpy", "Ekans", "Sandshrew", "Cubone", "Mankey", "Venonat"],
    "Viridian City": ["Poliwag", "Magikarp", "Hoothoot", "Ledyba", "Spinarak", "Pineco", "Wurmple", "Psyduck", "Slowpoke", "Goldeen", "Tentacool"],
    "Viridian Forest": ["Caterpie", "Weedle", "Pidgey", "Oddish", "Bellsprout", "Pichu", "Bulbasaur", "Hoothoot", "Kricketot", "Seedot", "Shroomish"],
    "Water Labyrinth": ["Tentacool", "Hoppip", "Krabby", "Horsea", "Qwilfish", "Remoraid", "Psyduck", "Slowpoke", "Magikarp", "Togepi"],
    "Water Path": ["Sentret", "Oddish", "Bellsprout", "Meowth", "Psyduck", "Slowpoke", "Spearow", "Tentacool", "Krabby", "Horsea", "Qwilfish", "Remoraid", "Magikarp"]
}

Johto = {
    "Route 29": ["Pidgey", "Sentret", "Hoothoot", "Rattata", "Exeggcute", "Ledyba", "Spinarak", "Pineco", "Hoppip", "Spearow", "Aipom", "Heracross"], 
    "Route 30": ["Caterpie", "Weedle", "Pidgey", "Rattata", "Hoothoot", "Ledyba", "Spinarak", "Poliwag", "Magikarp", "Exeggcute", "Pineco", "Zubat", "Azurill", "Spearow", "Aipom", "Heracross", "Hoppip"], 
    "Route 31": ["Caterpie", "Weedle", "Pidgey", "Rattata", "Hoothoot", "Ledyba", "Spinarak", "Bellsprout", "Poliwag", "Magikarp", "Exeggcute", "Pineco", "Zubat", "Gastly", "Hoppip", "Spearow", "Aipom", "Heracross"], 
    "Route 32": ["Rattata", "Ekans", "Bellsprout", "Wooper", "Zubat", "Mareep", "Hoppip", "Qwilfish", "Tentacool", "Magikarp", "Exeggcute", "Hoothoot", "Pineco", "Pidgey", "Gastly", "Spearow", "Aipom", "Heracross"], 
    "Route 33": ["Rattata", "Ekans", "Zubat", "Hoppip", "Spearow", "Aipom", "Heracross", "Geodude"], 
    "Route 34": ["Rattata", "Drowzee", "Ditto", "Abra", "Ralts", "Tentacool", "Exeggcute", "Hoothoot", "Ledyba", "Spinarak", "Pineco", "Snubbull", "Igglybuff", "Pidgey", "Krabby", "Staryu", "Corsola", "Magikarp", "Pichu", "Cleffa", "Tyrogue", "Smoochum", "Elekid", "Magby", "Caterpie", "Weedle"], 
    "Route 35": ["Nidoran M", "Nidoran F", "Pidgey", "Ditto", "Hoothoot", "Yanma", "Abra", "Drowzee", "Psyduck", "Poliwag", "Magikarp", "Exeggcute", "Ledyba", "Spinarak", "Pineco", "Snubbull", "Igglybuff", "Growlithe", "Spearow", "Caterpie", "Weedle"], 
    "Route 36": ["Pidgey", "Nidoran M", "Nidoran F", "Hoothoot", "Stantler", "Vulpix", "Growlithe", "Bonsly", "Exeggcute", "Ledyba", "Spinarak", "Pineco", "Gastly", "Bellsprout", "Caterpie", "Weedle"], 
    "Route 37": ["Pidgey", "Hoothoot", "Ledyba", "Spinarak", "Stantler", "Vulpix", "Growlithe", "Exeggcute", "Pineco", "Caterpie", "Weedle"], 
    "Route 38": ["Rattata", "Meowth", "Tauros", "Miltank", "Snubbull", "Magnemite", "Farfetch'd", "Exeggcute", "Hoothoot", "Ledyba", "Spinarak", "Pineco", "Burmy", "Caterpie", "Weedle"], 
    "Route 39": ["Rattata", "Meowth", "Tauros", "Miltank", "Snubbull", "Magnemite", "Farfetch'd", "Exeggcute", "Hoothoot", "Ledyba", "Spinarak", "Pineco", "Pidgey", "Caterpie", "Weedle"], 
    "Route 40": ["Tentacool", "Krabby", "Staryu", "Corsola", "Magikarp", "Shuckle"], 
    "Route 41": ["Tentacool", "Mantyke", "Shellder", "Chinchou", "Magikarp", "Krabby", "Staryu", "Corsola"], 
    "Route 42": ["Spearow", "Zubat", "Mankey", "Mareep", "Goldeen", "Magikarp", "Aipom", "Heracross", "Rattata", "Ekans", "Azurill"], 
    "Route 43": ["Pidgey", "Mareep", "Girafarig", "Venonat", "Hoothoot", "Magikarp", "Poliwag", "Exeggcute", "Pineco", "Rattata", "Sentret", "Farfetch'd", "Spearow", "Aipom", "Heracross"], 
    "Route 44": ["Bellsprout", "Tangela", "Lickitung", "Remoraid", "Poliwag", "Magikarp", "Spearow", "Aipom", "Heracross"], 
    "Route 45": ["Geodude", "Skarmory", "Gligar", "Teddiursa", "Phanpy", "Swablu", "Magikarp", "Poliwag", "Spearow", "Aipom", "Heracross", "Dratini"], 
    "Route 46": ["Rattata", "Spearow", "Geodude", "Aipom", "Heracross", "Igglybuff", "Phanpy"], 
    "Route 47": ["Ditto", "Rattata", "Spearow", "Oddish", "Farfetch'd", "Hoothoot", "Miltank", "Tentacool", "Seel", "Staryu", "Shellder", "Chinchou", "Magikarp", "Exeggcute", "Ledyba", "Spinarak", "Pineco", "Heracross", "Caterpie", "Weedle"], 
    "Route 48": ["Vulpix", "Growlithe", "Diglett", "Girafarig", "Spearow", "Oddish", "Farfetch'd", "Tauros", "Hoppip", "Exeggcute", "Hoothoot", "Ledyba", "Spinarak", "Pineco"], 
    "Azalea Town": ["Spearow", "Aipom", "Heracross", "Ekans", "Caterpie", "Weedle", "Exeggcute", "Pineco"], 
    "Bell Tower": ["Rattata", "Gastly", "Ho-oh"], 
    "Blackthorn City": ["Magikarp", "Poliwag", "Doduo", "Rhyhorn"], 
    "Burned Tower": ["Rattata", "Koffing", "Zubat", "Magby", "Krabby", "Shuckle"], 
    "Cherrygrove City": ["Tentacool", "Exeggcute", "Hoothoot", "Ledyba", "Spinarak", "Pineco", "Taillow", "Krabby", "Staryu", "Corsola", "Magikarp"], 
    "Cianwood City": ["Tentacool", "Krabby", "Shuckle", "Staryu", "Corsola", "Magikarp"], 
    "Cliff Cave": ["Zubat", "Machop", "Geodude", "Wooper", "Misdreavus", "Onix", "Krabby"], 
    "Cliff Edge Gate": ["Wooper", "Magikarp", "Poliwag"], 
    "Dark Cave": ["Zubat", "Geodude", "Wynaut", "Magikarp", "Goldeen", "Dunsparce", "Teddiursa", "Shuckle", "Krabby"], 
    "Dragon's Den": ["Magikarp", "Dratini"], 
    "Ecruteak City": ["Poliwag", "Magikarp", "Exeggcute", "Ledyba", "Spinarak", "Pineco"], 
    "Embedded Tower": ["Kyogre", "Groudon", "Rayquaza"], 
    "Goldenrod City": ["Eevee", "Machop", "Ekans", "Sandshrew", "Abra", "Dratini", "Cubone", "Wynaut"], 
    "Hoenn Sound": ["Zigzagoon", "Whismur", "Makuhita", "Plusle", "Minun", "Numel", "Spoink", "Spinda", "Absol"], 
    "Ice Path": ["Zubat", "Swinub", "Smoochum", "Delibird", "Sneasel"], 
    "Ilex Forest": ["Caterpie", "Weedle", "Zubat", "Oddish", "Paras", "Psyduck", "Poliwag", "Magikarp", "Pichu", "Hoothoot", "Pineco", "Pidgey", "Venonat", "Celebi", "Exeggcute"], 
    "Lake Of Rage": ["Magikarp", "Venonat", "Exeggcute", "Hoothoot", "Pineco", "Caterpie", "Weedle"], 
    "Mt. Mortar": ["Machop", "Geodude", "Zubat", "Rattata", "Azurill", "Goldeen", "Magikarp", "Tyrogue"], 
    "Mt. Silver": ["Onix", "Teddiursa", "Phanpy", "Zubat", "Larvitar", "Geodude", "Goldeen", "Magikarp", "Wooper", "Misdreavus", "Psyduck", "Moltres", "Sneasel", "Ponyta", "Tangela", "Doduo", "Poliwag", "Natu", "Aipom", "Heracross", "Magby", "Machop", "Paras"], 
    "National Park": ["Caterpie", "Weedle", "Hoothoot", "Sunkern", "Pidgey", "Exeggcute", "Ledyba", "Spinarak", "Pineco", "Cherubi", "Scyther", "Pinsir", "Wurmple", "Combee", "Paras", "Venonat", "Nincada", "Volbeat", "Illumise", "Kricketot", "Nidoran M", "Nidoran F", "Psyduck"], 
    "New Bark Town": ["Tentacool", "Shellder", "Chinchou", "Magikarp", "Chikorita", "Cyndaquil", "Totodile", "Exeggcute", "Hoothoot", "Ledyba", "Spinarak", "Pineco"], 
    "Olivine City": ["Tentacool", "Voltorb", "Onix", "Krabby", "Staryu", "Corsola", "Magikarp"], 
    "Roaming Johto": ["Raikou", "Entei", "Suicune"], 
    "Ruins of Alph": ["Unown", "Natu", "Smeargle", "Wooper", "Poliwag", "Magikarp", "Geodude"], 
    "Safari Zone": ["Spearow", "Paras", "Geodude", "Slowpoke", "Magnemite", "Magby", "Wynaut", "Zigzagoon", "Slakoth", "Aron", "Zangoose", "Spheal", "Bronzor", "Sandshrew", "Cubone", "Lotad", "Spinda", "Trapinch", "Cacnea", "Hippopotas", "Carnivine", "Rattata", "Abra", "Ponyta", "Girafarig", "Houndour", "Stantler", "Smeargle", "Surskit", "Electrike", "Shinx", "Cleffa", "Poliwag", "Happiny", "Magikarp", "Azurill", "Hoppip", "Sunkern", "Wooper", "Seedot", "Nosepass", "Riolu", "Pidgey", "Bellsprout", "Gastly", "Lickitung", "Mime Jr.", "Elekid", "Misdreavus", "Shuppet", "Beldum", "Bidoof", "Budew", "Igglybuff", "Drowzee", "Voltorb", "Goldeen", "Dratini", "Sentret", "Murkrow", "Duskull", "Chingling", "Bagon", "Buizel", "Pachirisu", "Ekans", "Oddish", "Diglett", "Grimer", "Koffing", "Shuckle", "Seviper", "Barboach", "Croagunk", "Zubat", "Krabby", "Larvitar", "Meditite", "Volbeat", "Lunatone", "Doduo", "Lapras", "Mareep", "Corphish", "Gible", "Machop", "Onix", "Kangaskhan", "Shroomish", "Illumise", "Solrock", "Skorupi", "Nidoran M", "Nidoran F", "Rhyhorn", "Tauros", "Torkoal", "Psyduck", "Farfetch'd", "Ditto"], 
    "Safari Zone Gate": ["Hoothoot", "Ledyba", "Spinarak", "Pineco", "Exeggcute"], 
    "Sinjoh Ruins": ["Dialga", "Palkia", "Giratina"], 
    "Sinnoh Sound": ["Meditite", "Bidoof", "Shinx", "Budew", "Buizel", "Chingling", "Bronzor", "Chatot", "Carnivine"],
    "Slowpoke Well": ["Zubat", "Slowpoke", "Goldeen", "Magikarp"],
    "Sprout Tower": ["Rattata", "Gastly"],
    "Team Rocket HQ": ["Geodude", "Voltorb", "Koffing"],
    "Tin Tower": ["Rattata", "Gastly", "Ho-oh", "Suicune"], 
    "Union Cave": ["Rattata", "Sandshrew", "Zubat", "Geodude", "Onix", "Wooper", "Goldeen", "Magikarp", "Tentacool", "Lapras", "Krabby", "Staryu", "Corsola", "Shellder", "Chinchou"], 
    "Violet City": ["Barboach", "Poliwag", "Magikarp", "Exeggcute", "Hoothoot", "Pineco", "Onix", "Togepi"], 
    "Whirl Island": ["Zubat", "Krabby", "Seel", "Tentacool", "Horsea", "Magikarp", "Lugia"]
}

Hoenn = {
    "Route 101": ["Wurmple", "Zigzagoon", "Poochyena", "Lillipup", "Zorua", "Sewaddle", "Chikorita", "Cyndaquil", "Totodile", "Treecko", "Torchic", "Mudkip", "Turtwig", "Chimchar", "Piplup", "Snivy", "Tepig", "Oshawott"],
    "Route 102": ["Zigzagoon", "Poochyena", "Wurmple", "Lotad", "Seedot", "Ralts", "Surskit", "Lillipup", "Gothita", "Tympole", "Azurill", "Corphish", "Magikarp", "Goldeen"],
    "Route 103": ["Zigzagoon", "Poochyena", "Wingull", "Lillipup", "Chatot", "Shellos", "Tentacool", "Wailmer", "Magikarp", "Carvanha"],
    "Route 104": ["Zigzagoon", "Wurmple", "Taillow", "Wingull", "Pidove", "Sewaddle", "Chatot", "Magikarp", "Poochyena", "Azurill"],
    "Route 105": ["Frillish", "Skrelp", "Clauncher", "Krabby", "Tentacool", "Wingull", "Wailmer", "Magikarp", "Regice", "Regigigas"],
    "Route 106": ["Frillish", "Skrelp", "Clauncher", "Krabby", "Tentacool", "Wingull", "Wailmer", "Magikarp"],
    "Route 107": ["Frillish", "Skrelp", "Clauncher", "Krabby", "Tentacool", "Wingull", "Wailmer", "Magikarp", "Chinchou", "Clamperl", "Relicanth"],
    "Route 108": ["Frillish", "Skrelp", "Clauncher", "Krabby", "Tentacool", "Wingull", "Wailmer", "Magikarp"],
    "Route 109": ["Frillish", "Skrelp", "Clauncher", "Krabby", "Tentacool", "Wingull", "Wailmer", "Magikarp"],
    "Route 110": ["Electrike", "Zigzagoon", "Gulpin", "Plusle", "Minun", "Oddish", "Wingull", "Voltorb", "Trubbish", "Chatot", "Shellos", "Magnemite", "Tentacool", "Wailmer", "Magikarp", "Poochyena"],
    "Route 111": ["Sandshrew", "Trapinch", "Cacnea", "Baltoy", "Sandile", "Dwebble", "Gible", "Azurill", "Surskit", "Barboach", "Magikarp", "Goldeen", "Geodude", "Regirock"],
    "Route 112": ["Numel", "Machop", "Ponyta", "Throh", "Sawk", "Tyrogue", "Azurill"],
    "Route 113": ["Spinda", "Sandshrew", "Skarmory", "Scraggy", "Klefki", "Bouffalant", "Slugma"],
    "Route 114": ["Swablu", "Lotad", "Seedot", "Zangoose", "Seviper", "Surskit", "Skorupi", "Misdreavus", "Tympole", "Azurill", "Barboach", "Magikarp", "Goldeen", "Geodude"],
    "Route 115": ["Swablu", "Taillow", "Igglybuff", "Wingull", "Pidove", "Misdreavus", "Cleffa", "Tentacool", "Wailmer", "Magikarp"],
    "Route 116": ["Zigzagoon", "Whismur", "Nincada", "Taillow", "Skitty", "Pidove", "Joltik", "Eevee", "Poochyena", "Abra"],
    "Route 117": ["Zigzagoon", "Budew", "Illumise", "Volbeat", "Azurill", "Oddish", "Surskit", "Rattata", "Deerling", "Tympole", "Corphish", "Magikarp", "Goldeen", "Poochyena", "Seedot"],
    "Route 118": ["Zigzagoon", "Electrike", "Wingull", "Kecleon", "Rattata", "Shinx", "Aipom", "Tentacool", "Carvanha", "Magikarp", "Goldeen"],
    "Route 119": ["Oddish", "Zigzagoon", "Tropius", "Kecleon", "Tentacool", "Wingull", "Feebas", "Carvanha", "Magikarp", "Castform", "Goldeen"],
    "Route 120": ["Oddish", "Azurill", "Kecleon", "Zigzagoon", "Tropius", "Absol", "Surskit", "Barboach", "Magikarp", "Tentacool", "Goldeen", "Registeel", "Poochyena", "Seedot"],
    "Route 121": ["Zigzagoon", "Shuppet", "Oddish", "Wingull", "Kecleon", "Elgyem", "Drowzee", "Aipom", "Duskull", "Poochyena", "Tentacool", "Wailmer", "Magikarp"],
    "Route 122": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Wailmer", "Magikarp", "Carvanha"],
    "Route 123": ["Shuppet", "Wingull", "Kecleon", "Oddish", "Zigzagoon", "Azurill", "Surskit", "Corphish", "Magikarp", "Goldeen", "Duskull", "Poochyena", "Tentacool", "Wailmer"],
    "Route 124": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Wailmer", "Magikarp", "Chinchou", "Clamperl", "Relicanth", "Carvanha"],
    "Route 125": ["Frillish", "Finneon", "Seel", "Tentacool", "Wingull", "Wailmer", "Magikarp", "Carvanha"],
    "Route 126": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Wailmer", "Magikarp", "Chinchou", "Clamperl", "Relicanth", "Carvanha"],
    "Route 127": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Wailmer", "Magikarp", "Carvanha"],
    "Route 128": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Luvdisc", "Wailmer", "Corsola", "Magikarp", "Chinchou", "Clamperl", "Relicanth"],
    "Route 129": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Wailmer", "Magikarp", "Chinchou", "Clamperl", "Relicanth", "Carvanha"],
    "Route 130": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Wailmer", "Horsea", "Magikarp", "Chinchou", "Clamperl", "Relicanth", "Carvanha"],
    "Route 131": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Wailmer", "Horsea", "Magikarp", "Carvanha"],
    "Route 132": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Wailmer", "Horsea", "Magikarp", "Carvanha"],
    "Route 133": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Wailmer", "Horsea", "Magikarp", "Carvanha"],
    "Route 134": ["Frillish", "Finneon", "Alomomola", "Tentacool", "Wingull", "Wailmer", "Horsea", "Magikarp", "Carvanha"],
    "Abandoned Ship": ["Tentacool", "Magikarp"],
    "Altering Cave": ["Zubat", "Mareep", "Aipom", "Pineco", "Shuckle", "Teddiursa", "Houndour", "Stantler", "Smeargle"],
    "Artisan Cave": ["Smeargle"],
    "Battle Resort": ["Tentacool", "Mantyke", "Wingull", "Remoraid", "Magikarp"],
    "Battle Tower": ["Meowth"],
    "Birth Island": ["Deoxys"],
    "Cave of Origin": ["Zubat", "Sableye", "Mawile", "Groudon", "Kyogre"],
    "Desert Underpass": ["Ditto", "Whismur"],
    "Dewford Town": ["Tentacool", "Wingull", "Wailmer", "Magikarp"],
    "Ever Grande City": ["Tentacool", "Wingull", "Luvdisc", "Wailmer", "Corsola", "Magikarp"],
    "Faraway Island": ["Mew"],
    "Fiery Path": ["Numel", "Koffing", "Slugma", "Machop", "Torkoal", "Grimer", "Roggenrola", "Diglett", "Tyrogue"],
    "Fortree City": ["Skitty", "Plusle"],
    "Granite Cave": ["Zubat", "Makuhita", "Abra", "Geodude", "Timburr", "Axew", "Onix", "Aron", "Sableye", "Mawile", "Nosepass"],
    "Jagged Pass": ["Numel", "Machop", "Spoink", "Ponyta", "Mankey", "Tyrogue"],
    "Lilycove City": ["Tentacool", "Wingull", "Wailmer", "Staryu", "Magikarp", "Geodude"],
    "Littleroot Town": ["Chikorita", "Cyndaquil", "Totodile"],
    "Marine Cave": ["Kyogre"],
    "Meteor Falls": ["Zubat", "Solrock", "Lunatone", "Deino", "Druddigon", "Cleffa", "Barboach", "Magikarp", "Goldeen", "Bagon"],
    "Mirage Island": ["Wynaut"],
    "Mirage Spots": ["Tangela", "Glameow", "Sunkern", "Minccino", "Venonat", "Blitzle", "Natu", "Maractus", "Geodude", "Binacle", "Meowth", "Audino", "Munna", "Ditto", "Darumaka", "Larvesta", "Porygon", "Pineco", "Phanpy", "Kricketot", "Stantler", "Rufflet", "Vullaby", "Vulpix", "Girafarig", "Magby", "Elekid", "Dwebble", "Happiny", "Klink", "Roggenrola", "Tynamo", "Drilbur", "Onix", "Yamask", "Slowpoke", "Unown", "Petilil", "Cherubi", "Cresselia", "Cobalion", "Terrakion", "Virizion"],
    "Mirage Tower": ["Sandshrew", "Trapinch"],
    "Mossdeep City": ["Tentacool", "Wingull", "Wailmer", "Magikarp", "Beldum", "Kecleon", "Carvanha"],
    "Mt. Pyre": ["Shuppet", "Duskull", "Meditite", "Vulpix", "Wingull", "Elgyem", "Bronzor", "Growlithe", "Chingling"],
    "New Mauville": ["Voltorb", "Magnemite"],
    "Pacifidlog Town": ["Tentacool", "Wingull", "Wailmer", "Magikarp", "Corsola", "Carvanha", "Horsea"],
    "Petalburg City": ["Azurill", "Surskit", "Corphish", "Magikarp", "Goldeen"],
    "Petalburg Woods": ["Zigzagoon", "Wurmple", "Taillow", "Shroomish", "Slakoth", "Cottonee", "Paras", "Phantump", "Poochyena"],
    "Roaming Hoenn": ["Latios", "Latias"],
    "Rustboro City": ["Omanyte", "Kabuto", "Aerodactyl", "Lileep", "Anorith", "Cranidos", "Shieldon", "Tirtouga", "Archen", "Tyrunt", "Amaura", "Makuhita", "Seedot"],
    "Rusturf Tunnel": ["Whismur", "Geodude"],
    "Safari Zone": ["Doduo", "Psyduck", "Oddish", "Rhyhorn", "Weedle", "Pidgey", "Buneary", "Heracross", "Goldeen", "Magikarp", "Phanpy", "Pinsir", "Natu", "Wynaut", "Pichu", "Girafarig", "Aipom", "Teddiursa", "Hoothoot", "Pineco", "Houndour", "Miltank", "Ledyba", "Sunkern", "Shuckle", "Geodude", "Mareep", "Gligar", "Snubbull", "Stantler", "Spinarak", "Azurill", "Wooper", "Remoraid"],
    "Scorched Slab": ["Zubat", "Barboach", "Magikarp", "Goldeen", "Heatran"],
    "Sea Mauville": ["Tentacool", "Wingull", "Wailmer", "Magikarp", "Spiritomb", "Ho-oh", "Lugia"],
    "Seafloor Cavern": ["Zubat", "Geodude", "Tentacool", "Wailmer", "Magikarp"],
    "Sealed Chamber": ["Tentacool", "Zubat", "Wailmer", "Horsea", "Magikarp"],
    "Shoal Cave": ["Zubat", "Spheal", "Snorunt", "Cubchoo", "Delibird", "Seel", "Geodude", "Tentacool", "Wailmer", "Magikarp"],
    "Sky Pillar": ["Zubat", "Baltoy", "Spinarak", "Sableye", "Mawile", "Swablu", "Shuppet", "Duskull", "Rayquaza", "Deoxys"],
    "Slateport City": ["Tentacool", "Wingull", "Wailmer", "Magikarp"],
    "Sootopolis City": ["Magikarp", "Tentacool"],
    "Soaring": ["Murkrow", "Taillow", "Wingull", "Swablu", "Drifloon", "Rufflet", "Dialga", "Palkia", "Giratina", "Tornadus", "Thundurus", "Landorus"],
    "Southern Island": ["Latios", "Latias"],
    "Team Magma/Aqua Hideout": ["Tentacool", "Wailmer", "Staryu", "Magikarp", "Voltorb", "Geodude", "Torkoal"],
    "Terra Cave": ["Groudon"],
    "Victory Road": ["Zubat", "Aron", "Makuhita", "Whismur", "Sableye", "Mawile", "Meditite", "Tentacool", "Luvdisc", "Wailmer", "Magikarp", "Barboach", "Goldeen", "Geodude"]
}

Sinnoh = {
    "Route 201": ["Starly", "Bidoof", "Kricketot", "Growlithe", "Doduo", "Turtwig", "Chimchar", "Piplup", "Nidoran M", "Nidoran F"],
    "Route 202": ["Starly", "Bidoof", "Shinx", "Kricketot", "Growlithe", "Zigzagoon", "Psyduck", "Goldeen", "Magikarp", "Sentret"],
    "Route 203": ["Starly", "Shinx", "Bidoof", "Zubat", "Abra", "Kricketot", "Pineco", "Seedot", "Lotad", "Cubone", "Psyduck", "Goldeen", "Magikarp", "Ralts"],
    "Route 204": ["Starly", "Bidoof", "Budew", "Zubat", "Kricketot", "Shinx", "Wurmple", "Pineco", "Caterpie", "Weedle", "Seedot", "Lotad", "Psyduck", "Goldeen", "Magikarp", "Sunkern", "Ralts"],
    "Route 205": ["Bidoof", "Buizel", "Budew", "Wurmple", "Pachirisu", "Shellos", "Hoothoot", "Kricketot", "Lotad", "Psyduck", "Magikarp", "Barboach", "Hoppip", "Slowpoke", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi", "Elekid", "Tentacool", "Wingull", "Finneon", "Shellder"],
    "Route 206": ["Geodude", "Ponyta", "Stunky", "Zubat", "Kricketot", "Bronzor", "Machop", "Gligar", "Nosepass", "Larvitar", "Baltoy", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Route 207": ["Machop", "Geodude", "Ponyta", "Zubat", "Kricketot", "Gligar", "Phanpy", "Stantler", "Larvitar", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Route 208": ["Psyduck", "Budew", "Zubat", "Machop", "Meditite", "Bidoof", "Ralts", "Zangoose", "Seviper", "Dunsparce", "Magikarp", "Barboach", "Goldeen", "Tyrogue", "Smeargle", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Route 209": ["Starly", "Bidoof", "Bonsly", "Mime Jr.", "Budew", "Happiny", "Zubat", "Gastly", "Ralts", "Duskull", "Vulpix", "Snubbull", "Psyduck", "Goldeen", "Magikarp", "Spiritomb", "Tauros", "Miltank", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Route 210": ["Meditite", "Swablu", "Scyther", "Psyduck", "Machop", "Hoothoot", "Bidoof", "Zangoose", "Seviper", "Magikarp", "Barboach", "Kecleon", "Bagon", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi", "Geodude", "Ponyta", "Kricketot", "Bonsly", "Mime Jr.", "Happiny", "Budew", "Pineco", "Seedot", "Tauros", "Miltank", "Starly"],
    "Route 211": ["Meditite", "Ponyta", "Zubat", "Machop", "Geodude", "Hoothoot", "Chingling", "Bronzor", "Teddiursa", "Swablu", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi", "Bidoof", "Tyrogue"],
    "Route 212": ["Starly", "Kricketot", "Budew", "Azurill", "Ralts", "Psyduck", "Goldeen", "Magikarp", "Smeargle", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi", "Wooper", "Bidoof", "Shellos", "Buizel", "Croagunk", "Ekans", "Lotad", "Tentacool", "Barboach", "Remoraid", "Grimer"],
    "Route 213": ["Buizel", "Shellos", "Wingull", "Chatot", "Absol", "Tentacool", "Magikarp", "Remoraid", "Carvanha", "Taillow", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Route 214": ["Ponyta", "Kricketot", "Geodude", "Rhyhorn", "Houndour", "Bonsly", "Girafarig", "Stunky", "Zubat", "Gligar", "Vulpix", "Spoink", "Psyduck", "Goldeen", "Magikarp", "Poochyena", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Route 215": ["Geodude", "Ponyta", "Kricketot", "Azurill", "Starly", "Scyther", "Abra", "Lickitung", "Gligar", "Drowzee", "Houndour", "Poochyena", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Route 216": ["Sneasel", "Snover", "Geodude", "Zubat", "Machop", "Hoothoot", "Meditite", "Snorunt", "Teddiursa", "Delibird"],
    "Route 217": ["Sneasel", "Snover", "Swinub", "Zubat", "Machop", "Hoothoot", "Meditite", "Snorunt", "Teddiursa", "Delibird"],
    "Route 218": ["Buizel", "Mime Jr.", "Shellos", "Wingull", "Glameow", "Chatot", "Voltorb", "Tentacool", "Magikarp", "Finneon", "Ditto", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Route 219": ["Tentacool", "Wingull", "Magikarp", "Finneon", "Clamperl"],
    "Route 220": ["Tentacool", "Wingull", "Magikarp", "Chinchou", "Finneon"],
    "Route 221": ["Buizel", "Bonsly", "Girafarig", "Budew", "Wingull", "Shellos", "Stunky", "Farfetch'd", "Tentacool", "Magikarp", "Finneon", "Clamperl", "Nidoran M", "Nidoran F", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Route 222": ["Buizel", "Shellos", "Elekid", "Magnemite", "Wingull", "Mime Jr.", "Glameow", "Chatot", "Shinx", "Skitty", "Tentacool", "Magikarp", "Remoraid", "Carvanha", "Mareep", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Route 223": ["Tentacool", "Wingull", "Mantyke", "Magikarp", "Wailmer", "Remoraid"],
    "Route 224": ["Buizel", "Shellos", "Oddish", "Bellsprout", "Wurmple", "Budew", "Chatot", "Wingull", "Shuckle", "Natu", "Tentacool", "Magikarp", "Remoraid", "Luvdisc", "Duskull"],
    "Route 225": ["Rattata", "Spearow", "Machop", "Budew", "Shuppet", "Stunky", "Geodude", "Makuhita", "Psyduck", "Poliwag", "Magikarp", "Barboach", "Mankey"],
    "Route 226": ["Rattata", "Spearow", "Machop", "Psyduck", "Shuppet", "Geodude", "Wingull", "Krabby", "Seel", "Spheal", "Tentacool", "Horsea", "Magikarp", "Relicanth", "Mankey"],
    "Route 227": ["Geodude", "Rhyhorn", "Skarmory", "Numel", "Spearow", "Zubat", "Koffing", "Shuppet", "Gligar", "Magby", "Spinda", "Poliwag", "Magikarp", "Barboach", "Torkoal"],
    "Route 228": ["Diglett", "Cacnea", "Rhyhorn", "Hippopotas", "Sandshrew", "Beldum", "Poliwag", "Magikarp", "Barboach", "Trapinch", "Regirock"],
    "Route 229": ["Oddish", "Bellsprout", "Pidgey", "Budew", "Scyther", "Pinsir", "Volbeat", "Illumise", "Wurmple", "Ledyba", "Spinarak", "Glameow", "Pineco", "Seedot", "Lotad", "Wingull", "Surskit", "Magikarp", "Goldeen", "Venonat"],
    "Route 230": ["Wingull", "Buizel", "Shellos", "Oddish", "Bellsprout", "Psyduck", "Wurmple", "Budew", "Corsola", "Seel", "Spheal", "Tentacool", "Magikarp", "Wailmer", "Remoraid", "Togepi"],
    "Acuity Lakefront": ["Sneasel", "Snover", "Swinub", "Zubat", "Machop", "Hoothoot", "Meditite", "Snorunt", "Teddiursa"],
    "Big Bluff Cavern": ["Geodude", "Onix", "Skorupi", "Bronzor", "Hippopotas", "Sandshrew", "Cubone", "Rhyhorn", "Tauros", "Sentret", "Gligar", "Shuckle", "Phanpy", "Larvitar", "Zigzagoon", "Aron", "Numel", "Trapinch", "Cacnea", "Baltoy", "Beldum", "Scyther", "Pinsir", "Absol"],
    "Bogsunk Cavern": ["Zubat", "Budew", "Skorupi", "Croagunk", "Barboach", "Wooper", "Tentacool", "Bulbasaur", "Caterpie", "Weedle", "Ekans", "Nidoran F", "Nidoran M", "Oddish", "Paras", "Venonat", "Bellsprout", "Grimer", "Koffing", "Tangela", "Ledyba", "Spinarak", "Pineco", "Qwilfish", "Cacnea", "Zangoose", "Seviper", "Tropius", "Lickitung", "Swinub", "Gligar"],
    "Canalave City": ["Tentacool", "Wingull", "Shellos", "Magikarp", "Finneon", "Staryu"],
    "Celestic Town": ["Psyduck", "Magikarp", "Corphish", "Barboach", "Goldeen"],
    "Dazzling Cave": ["Gastly", "Misdreavus", "Meditite", "Chingling", "Bronzor", "Abra", "Girafarig", "Mime Jr.", "Nidoran F", "Nidoran M", "Slowpoke", "Grimer", "Drowzee", "Krabby", "Voltorb", "Cubone", "Ditto", "Togepi", "Natu", "Wynaut", "Snubbull", "Houndour", "Smoochum", "Elekid", "Poochyena", "Ralts", "Sableye", "Mawile", "Volbeat", "Illumise", "Zangoose", "Seviper", "Lunatone", "Solrock", "Baltoy", "Shuppet", "Duskull", "Absol", "Bagon"],
    "Distortion World": ["Giratina"],
    "Eterna City": ["Psyduck", "Magikarp", "Barboach", "Togepi", "Chatot"],
    "Eterna Forest": ["Wurmple", "Budew", "Gastly", "Murkrow", "Misdreavus", "Buneary", "Hoothoot", "Bidoof", "Kricketot", "Pineco", "Caterpie", "Weedle", "Seedot", "Slakoth", "Nincada", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Floaroma Meadow": ["Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Floaroma Town": ["Mew", "Jirachi"],
    "Flower Paradise": ["Shaymin"],
    "Fountainspring Cave": ["Psyduck", "Bidoof", "Buizel", "Shellos", "Hoothoot", "Barboach", "Wooper", "Wingull", "Tentacool", "Gible", "Remoraid", "Mantyke", "Squirtle", "Poliwag", "Slowpoke", "Farfetch'd", "Seel", "Shellder", "Horsea", "Staryu", "Tauros", "Dratini", "Totodile", "Ledyba", "Chinchou", "Qwilfish", "Corsola", "Mudkip", "Lotad", "Surskit", "Carvanha", "Corphish", "Clamperl", "Piplup", "Lickitung", "Ralts", "Swablu", "Togepi"],
    "Fuego Ironworks": ["Buizel", "Magnemite", "Magby", "Shellos", "Wingull", "Shinx", "Pachirisu", "Tentacool", "Finneon", "Magikarp", "Shellder", "Hoppip", "Aron", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Glacial Cavern": ["Buneary", "Bronzor", "Mime Jr.", "Sneasel", "Snover", "Magnemite", "Seel", "Staryu", "Tauros", "Chinchou", "Teddiursa", "Swinub", "Delibird", "Smoochum", "Poochyena", "Aron", "Swablu", "Snorunt", "Spheal", "Beldum", "Elekid"],
    "Grassland Cave": ["Zubat", "Machop", "Murkrow", "Wurmple", "Budew", "Bidoof", "Kricketot", "Shinx", "Combee", "Cherubi", "Buneary", "Hoothoot", "Stunky", "Glameow", "Munchlax", "Bulbasaur", "Caterpie", "Weedle", "Rattata", "Ekans", "Nidoran F", "Nidoran M", "Oddish", "Paras", "Venonat", "Mankey", "Poliwag", "Bellsprout", "Slowpoke", "Farfetch'd", "Doduo", "Scyther", "Pinsir", "Tauros", "Chikorita", "Ledyba", "Spinarak", "Mareep", "Hoppip", "Sunkern", "Pineco", "Shuckle", "Teddiursa", "Tyrogue", "Miltank", "Treecko", "Lotad", "Seedot", "Nincada", "Volbeat", "Illumise", "Trapinch", "Cacnea", "Zangoose", "Seviper", "Kecleon", "Tropius", "Absol", "Turtwig"],
    "Great Marsh": ["Wooper", "Psyduck", "Azurill", "Bidoof", "Tangela", "Yanma", "Hoothoot", "Starly", "Budew", "Tropius", "Ekans", "Carvanha", "Barboach", "Magikarp", "Paras", "Exeggcute", "Kangaskhan", "Shroomish", "Gulpin", "Skorupi", "Croagunk", "Carnivine", "Kecleon"],
    "Hall of Origin": ["Arceus"],
    "Hearthome City": ["Eevee", "Happiny"],
    "Icy Cave": ["Buneary", "Bronzor", "Mime Jr.", "Sneasel", "Snover", "Magnemite", "Seel", "Staryu", "Tauros", "Chinchou", "Teddiursa", "Swinub", "Delibird", "Smoochum", "Poochyena", "Aron", "Swablu", "Snorunt", "Spheal", "Beldum"],
    "Iron Island": ["Geodude", "Zubat", "Onix", "Mawile", "Sableye", "Riolu", "Tentacool", "Wingull", "Magikarp", "Finneon", "Qwilfish", "Registeel"],
    "Lake Acuity": ["Psyduck", "Sneasel", "Bidoof", "Snover", "Hoothoot", "Chingling", "Snorunt", "Teddiursa", "Solrock", "Lunatone", "Smoochum", "Goldeen", "Magikarp", "Wynaut", "Uxie"],
    "Lake Valor": ["Starly", "Bidoof", "Psyduck", "Hoothoot", "Chingling", "Solrock", "Lunatone", "Lickitung", "Goldeen", "Magikarp", "Wynaut", "Azelf"],
    "Lake Verity": ["Starly", "Bidoof", "Solrock", "Lunatone", "Surskit", "Psyduck", "Goldeen", "Magikarp", "Turtwig", "Chimchar", "Piplup", "Wynaut"],
    "Lost Tower": ["Zubat", "Gastly", "Murkrow", "Misdreavus", "Duskull"],
    "Maniac Tunnel": ["Geodude", "Hippopotas"],
    "Mt. Coronet": ["Geodude", "Bronzor", "Zubat", "Nosepass", "Cleffa", "Machop", "Meditite", "Chingling", "Solrock", "Lunatone", "Magikarp", "Barboach", "Dratini", "Feebas", "Snover", "Absol", "Hoothoot", "Whismur", "Regice"],
    "Newmoon Island": ["Darkrai"],
    "Old Chateau": ["Gastly", "Rotom"],
    "Oreburgh City": ["Omanyte", "Kabuto", "Aerodactyl", "Lileep", "Anorith", "Cranidos", "Shieldon", "Abra"],
    "Oreburgh Gate": ["Geodude", "Zubat", "Psyduck", "Magikarp", "Barboach"],
    "Oreburgh Mine": ["Geodude", "Zubat", "Onix"],
    "Pastoria City": ["Tentacool", "Wingull", "Shellos", "Magikarp", "Remoraid"],
    "Pokémon League": ["Tentacool", "Wingull", "Magikarp", "Remoraid", "Luvdisc"],
    "Ramanas Park": ["Articuno", "Zapdos", "Moltres", "Raikou", "Entei", "Suicune", "Ho-oh", "Lugia", "Mewtwo", "Kyogre", "Groudon", "Rayquaza", "Regirock", "Regice", "Registeel", "Latias", "Latios"],
    "Ravaged Path": ["Zubat", "Psyduck", "Geodude", "Magikarp", "Barboach"],
    "Resort Area": ["Psyduck", "Goldeen", "Magikarp"],
    "Riverbank Cave": ["Psyduck", "Murkrow", "Wurmple", "Bidoof", "Kricketot", "Budew", "Buizel", "Buneary", "Croagunk", "Hoothoot", "Barboach", "Stunky", "Wingull", "Glameow", "Munchlax", "Tentacool", "Gible", "Remoraid", "Mantyke", "Bulbasaur", "Squirtle", "Caterpie", "Weedle", "Rattata", "Ekans", "Nidoran F", "Nidoran M", "Oddish", "Venonat", "Poliwag", "Bellsprout", "Slowpoke", "Shellder", "Cubone", "Horsea", "Staryu", "Scyther", "Pinsir", "Tauros", "Chikorita", "Totodile", "Ledyba", "Qwilfish", "Shuckle", "Corsola", "Tyrogue", "Treecko", "Mudkip", "Lotad", "Seedot", "Surskit", "Nincada", "Carvanha", "Lunatone", "Solrock", "Corphish", "Kecleon", "Clamperl", "Turtwig", "Piplup", "Lickitung"],
    "Roaming Sinnoh": ["Mesprit", "Cresselia", "Articuno", "Zapdos", "Moltres"],
    "Rocky Cave": ["Geodude", "Onix", "Skorupi", "Bronzor", "Hippopotas", "Sandshrew", "Cubone", "Rhyhorn", "Tauros", "Sentret", "Gligar", "Shuckle", "Phanpy", "Larvitar", "Zigzagoon", "Aron", "Numel", "Trapinch", "Cacnea", "Baltoy", "Beldum", "Teddiursa"],
    "Sandsear Cave": ["Onix", "Skorupi", "Ponyta", "Hippopotas", "Charmander", "Sandshrew", "Vulpix", "Growlithe", "Rhyhorn", "Cyndaquil", "Slugma", "Houndour", "Magby", "Torchic", "Numel", "Torkoal", "Trapinch", "Chimchar"],
    "Sendoff Spring": ["Starly", "Bidoof", "Geodude", "Duskull", "Psyduck", "Hoothoot", "Chingling", "Zubat", "Solrock", "Lunatone", "Goldeen", "Magikarp"],
    "Snowpoint City": ["Gastly"],
    "Snowpoint Temple": ["Zubat", "Sneasel", "Onix", "Geodude", "Smoochum", "Regigigas"],
    "Solaceon Ruins": ["Unown"],
    "Spacious Cave": ["Zubat", "Psyduck", "Machop", "Geodude", "Murkrow", "Bidoof", "Kricketot", "Shinx", "Budew", "Pachirisu", "Buneary", "Hoothoot", "Chingling", "Stunky", "Aipom", "Wingull", "Glameow", "Munchlax", "Mantyke", "Caterpie", "Weedle", "Rattata", "Sandshrew", "Vulpix", "Oddish", "Venonat", "Mankey", "Growlithe", "Slowpoke", "Magnemite", "Farfetch'd", "Doduo", "Krabby", "Voltorb", "Lickitung", "Rhyhorn", "Tauros", "Sentret", "Natu", "Teddiursa", "Houndour", "Tyrogue", "Miltank", "Poochyena", "Zigzagoon", "Skitty", "Swablu", "Corphish", "Absol", "Bagon"],
    "Spear Pillar": ["Dialga", "Palkia"],
    "Stargleam Cavern": ["Gastly", "Misdreavus", "Meditite", "Chingling", "Bronzor", "Abra", "Girafarig", "Mime Jr.", "Nidoran F", "Nidoran M", "Slowpoke", "Grimer", "Drowzee", "Krabby", "Voltorb", "Cubone", "Ditto", "Togepi", "Natu", "Wynaut", "Snubbull", "Houndour", "Smoochum", "Elekid", "Poochyena", "Ralts", "Sableye", "Mawile", "Volbeat", "Illumise", "Zangoose", "Seviper", "Lunatone", "Solrock", "Baltoy", "Shuppet", "Duskull", "Absol", "Bagon"],
    "Stark Mountain": ["Slugma", "Geodude", "Onix", "Numel", "Rhyhorn", "Machop", "Zubat", "Koffing", "Magby", "Skarmory", "Spearow", "Shuppet", "Gligar", "Torkoal", "Heatran"],
    "Still-Water Cavern": ["Psyduck", "Murkrow", "Wurmple", "Bidoof", "Kricketot", "Budew", "Buizel", "Buneary", "Croagunk", "Hoothoot", "Barboach", "Stunky", "Wingull", "Glameow", "Munchlax", "Tentacool", "Gible", "Remoraid", "Mantyke", "Bulbasaur", "Squirtle", "Caterpie", "Weedle", "Rattata", "Ekans", "Nidoran F", "Nidoran M", "Oddish", "Venonat", "Poliwag", "Bellsprout", "Slowpoke", "Shellder", "Cubone", "Horsea", "Staryu", "Scyther", "Pinsir", "Tauros", "Chikorita", "Totodile", "Ledyba", "Qwilfish", "Shuckle", "Corsola", "Tyrogue", "Treecko", "Mudkip", "Lotad", "Seedot", "Surskit", "Nincada", "Carvanha", "Lunatone", "Solrock", "Corphish", "Kecleon", "Clamperl", "Turtwig", "Piplup", "Lickitung"],
    "Sunlit Cavern": ["Zubat", "Machop", "Murkrow", "Wurmple", "Budew", "Bidoof", "Kricketot", "Shinx", "Combee", "Cherubi", "Buneary", "Hoothoot", "Stunky", "Glameow", "Munchlax", "Bulbasaur", "Caterpie", "Weedle", "Rattata", "Ekans", "Nidoran F", "Nidoran M", "Oddish", "Paras", "Venonat", "Mankey", "Poliwag", "Bellsprout", "Slowpoke", "Farfetch'd", "Doduo", "Scyther", "Pinsir", "Tauros", "Chikorita", "Ledyba", "Spinarak", "Mareep", "Hoppip", "Sunkern", "Pineco", "Shuckle", "Teddiursa", "Tyrogue", "Miltank", "Treecko", "Lotad", "Seedot", "Nincada", "Volbeat", "Illumise", "Trapinch", "Cacnea", "Zangoose", "Seviper", "Kecleon", "Tropius", "Absol", "Turtwig", "Rhyhorn", "Gligar", "Teddiursa"],
    "Sunyshore City": ["Tentacool", "Wingull", "Mantyke", "Magikarp", "Remoraid", "Staryu"],
    "Swampy Cave": ["Zubat", "Budew", "Skorupi", "Croagunk", "Barboach", "Wooper", "Tentacool", "Bulbasaur", "Caterpie", "Weedle", "Ekans", "Nidoran F", "Nidoran M", "Oddish", "Paras", "Venonat", "Bellsprout", "Grimer", "Koffing", "Tangela", "Ledyba", "Spinarak", "Pineco", "Qwilfish", "Cacnea", "Zangoose", "Seviper", "Tropius", "Lickitung", "Swinub", "Gligar"],
    "Trophy Garden": ["Pichu", "Budew", "Starly", "Kricketot", "Cleffa", "Igglybuff", "Meowth", "Happiny", "Eevee", "Porygon", "Azurill", "Plusle", "Minun", "Castform", "Bonsly", "Mime Jr.", "Ditto"],
    "Turnback Cave": ["Zubat", "Gastly", "Bronzor", "Duskull", "Chingling", "Solrock", "Lunatone", "Giratina"],
    "Twinleaf Town": ["Psyduck", "Goldeen", "Magikarp"],
    "Typhlo Cavern": ["Geodude", "Onix", "Skorupi", "Ponyta", "Charmander", "Vulpix", "Growlithe", "Cyndaquil", "Sentret", "Slugma", "Magby", "Torchic", "Numel", "Torkoal", "Chimchar", "Rhyhorn", "Houndour"],
    "Valley Windworks": ["Pachirisu", "Buizel", "Shellos", "Bidoof", "Shinx", "Elekid", "Electrike", "Tentacool", "Wingull", "Magikarp", "Finneon", "Shellder", "Drifloon", "Mareep", "Wurmple", "Munchlax", "Heracross", "Aipom", "Burmy", "Combee", "Cherubi"],
    "Valor Lakefront": ["Girafarig", "Kricketot", "Starly", "Bidoof", "Geodude", "Houndour", "Nidoran M", "Nidoran F"],
    "Veilstone City": ["Porygon"],
    "Victory Road": ["Machop", "Geodude", "Zubat", "Onix", "Gible", "Meditite", "Rhyhorn", "Abra", "Magnemite", "Buizel", "Azurill", "Magikarp", "Remoraid", "Seel", "Lapras"],
    "Volcanic Cave": ["Geodude", "Onix", "Skorupi", "Ponyta", "Charmander", "Vulpix", "Growlithe", "Cyndaquil", "Sentret", "Slugma", "Magby", "Torchic", "Numel", "Torkoal", "Chimchar", "Houndour"],
    "Wayward Cave": ["Zubat", "Bronzor", "Geodude", "Onix", "Sandshrew", "Gible"],
    "Whiteout Cave": ["Machop", "Shinx", "Pachirisu", "Buneary", "Meditite", "Munchlax", "Mime Jr.", "Sneasel", "Snover", "Magnemite", "Seel", "Tauros", "Sentret", "Mareep", "Teddiursa", "Swinub", "Delibird", "Tyrogue", "Elekid", "Aron", "Swablu", "Snorunt", "Spheal", "Beldum"]
}

Unova = {
    "Route 1": ["Patrat", "Lillipup", "Igglybuff", "Scraggy", "Audino", "Dunsparce", "Farfetch'd", "Basculin", "Feebas"],
    "Route 2": ["Patrat", "Lillipup", "Purrloin", "Igglybuff", "Lickitung", "Audino", "Dunsparce", "Wynaut"],
    "Route 3": ["Pidove", "Patrat", "Lillipup", "Purrloin", "Blitzle", "Yanma", "Audino", "Volbeat", "Illumise", "Basculin", "Corphish", "Goldeen"],
    "Route 4": ["Sandile", "Darumaka", "Trubbish", "Minccino", "Scraggy", "Hippopotas", "Frillish", "Alomomola", "Krabby", "Clamperl", "Finneon", "Luvdisc", "Qwilfish", "Relicanth", "Rufflet", "Vullaby", "Cottonee", "Petilil"],
    "Route 5": ["Minccino", "Gothita", "Solosis", "Purrloin", "Trubbish", "Audino", "Emolga", "Smeargle"],
    "Route 6": ["Deerling", "Karrablast", "Shelmet", "Azurill", "Pidove", "Sewaddle", "Vanillite", "Foongus", "Audino", "Castform", "Emolga", "Dunsparce", "Plusle", "Minun", "Basculin", "Poliwag"],
    "Route 7": ["Pidove", "Cubchoo", "Zangoose", "Seviper", "Foongus", "Patrat", "Blitzle", "Deerling", "Audino", "Emolga", "Sentret", "Roggenrola"],
    "Route 8": ["Tympole", "Shelmet", "Karrablast", "Stunfisk", "Croagunk", "Barboach"],
    "Route 9": ["Gothita", "Solosis", "Minccino", "Grimer", "Purrloin", "Trubbish", "Pawniard", "Audino", "Emolga", "Houndour", "Poochyena"],
    "Route 10": ["Lillipup", "Rufflet", "Vullaby", "Throh", "Sawk", "Foongus", "Bouffalant", "Audino", "Emolga", "Tyrogue"],
    "Route 11": ["Rufflet", "Vullaby", "Karrablast", "Shelmet", "Pawniard", "Foongus", "Psyduck", "Gligar", "Zangoose", "Seviper", "Azurill", "Audino", "Emolga", "Paras", "Shroomish", "Buizel", "Basculin", "Goldeen", "Virizion"],
    "Route 12": ["Budew", "Pidove", "Pinsir", "Dunsparce", "Heracross", "Caterpie", "Weedle", "Ponyta", "Sunkern", "Combee", "Cherubi", "Sewaddle", "Audino", "Emolga", "Doduo"],
    "Route 13": ["Tangela", "Wingull", "Zubat", "Taillow", "Solrock", "Lunatone", "Absol", "Drifloon", "Audino", "Emolga", "Shuppet", "Staryu", "Frillish", "Basculin", "Corsola", "Shellder", "Krabby", "Luvdisc", "Cobalion"],
    "Route 14": ["Psyduck", "Shuckle", "Swablu", "Igglybuff", "Tropius", "Drifloon", "Elgyem", "Mienfoo", "Absol", "Audino", "Emolga", "Yanma", "Buizel", "Basculin", "Goldeen"],
    "Route 15": ["Spearow", "Sandshrew", "Gligar", "Cubone", "Kangaskhan", "Larvitar", "Throh", "Sawk", "Scraggy", "Patrat", "Audino", "Emolga", "Mankey", "Rotom"],
    "Route 16": ["Minccino", "Gothita", "Solosis", "Purrloin", "Trubbish", "Audino", "Emolga", "Pineco"],
    "Route 17": ["Frillish", "Alomomola", "Horsea", "Finneon"],
    "Route 18": ["Dwebble", "Scraggy", "Patrat", "Throh", "Sawk", "Tropius", "Carnivine", "Audino", "Dunsparce", "Exeggcute", "Frillish", "Alomomola", "Horsea", "Finneon", "Chinchou", "Corsola", "Larvesta"],
    "Route 19": ["Patrat", "Purrloin", "Basculin", "Poliwag"],
    "Route 20": ["Sunkern", "Pidove", "Sewaddle", "Patrat", "Purrloin", "Venipede", "Audino", "Dunsparce", "Azurill", "Basculin", "Poliwag"],
    "Route 21": ["Mantyke", "Frillish", "Remoraid", "Alomomola", "Luvdisc"],
    "Route 22": ["Mienfoo", "Delibird", "Psyduck", "Azurill", "Wingull", "Solrock", "Lunatone", "Foongus", "Audino", "Emolga", "Basculin", "Goldeen", "Terrakion"],
    "Route 23": ["Throh", "Sawk", "Bouffalant", "Rufflet", "Vullaby", "Psyduck", "Gligar", "Foongus", "Mienfoo", "Audino", "Emolga", "Buizel", "Basculin", "Poliwag", "Azelf"],
    "Abundant Shrine": ["Chingling", "Cottonee", "Petilil", "Murkrow", "Misdreavus", "Swablu", "Vulpix", "Hoothoot", "Stantler", "Bronzor", "Psyduck", "Azurill", "Audino", "Emolga", "Slowpoke", "Basculin", "Goldeen", "Landorus"],
    "Accumula Town": ["Abra", "Aipom"],
    "Aspertia City": ["Basculin", "Goldeen", "Snivy", "Tepig", "Oshawott"],
    "Castelia City": ["Rattata", "Cottonee", "Petilil", "Eevee", "Skitty", "Buneary", "Pidove", "Audino", "Zorua"],
    "Castelia Sewers": ["Rattata", "Zubat", "Grimer"],
    "Celestial Tower": ["Litwick", "Zubat", "Elgyem", "Mesprit"],
    "Challenger's Cave": ["Geodude", "Lickitung", "Sableye", "Mawile", "Roggenrola", "Woobat", "Drilbur", "Riolu", "Basculin", "Poliwag"],
    "Chargestone Cave": ["Joltik", "Klink", "Tynamo", "Roggenrola", "Ferroseed", "Nosepass", "Drilbur"],
    "Clay Tunnel": ["Roggenrola", "Onix", "Nosepass", "Aron", "Woobat", "Durant", "Drilbur", "Basculin", "Poliwag"],
    "Cold Storage": ["Lillipup", "Vanillite", "Timburr", "Minccino", "Audino"],
    "Desert Resort": ["Sandile", "Darumaka", "Trapinch", "Maractus", "Dwebble", "Sigilyph", "Sandshrew", "Scraggy"],
    "Dragonspiral Tower": ["Druddigon", "Golett", "Mienfoo", "Pidove", "Vanillite", "Deerling", "Cubchoo", "Audino", "Emolga", "Basculin", "Dratini", "Reshiram", "Zekrom"],
    "Dreamyard": ["Rattata", "Kricketot", "Ledyba", "Spinarak", "Munna", "Zubat", "Igglybuff", "Patrat", "Purrloin", "Venonat", "Audino", "Dunsparce", "Pansage", "Pansear", "Panpour", "Latias", "Latios"],
    "Driftveil City": ["Frillish", "Alomomola", "Krabby", "Chinchou", "Luvdisc", "Basculin"],
    "Driftveil Drawbridge": ["Ducklett"],
    "Floccesy Ranch": ["Lillipup", "Riolu", "Pidove", "Psyduck", "Mareep", "Azurill", "Patrat", "Audino", "Dunsparce", "Basculin", "Poliwag"],
    "Giant Chasm": ["Swinub", "Roggenrola", "Delibird", "Zubat", "Smoochum", "Sneasel", "Solrock", "Lunatone", "Cleffa", "Vanillite", "Drilbur", "Seel", "Basculin", "Poliwag", "Tangela", "Taillow", "Absol", "Drifloon", "Wingull", "Audino", "Ditto", "Beldum", "Kyurem"],
    "Humilau City": ["Staryu", "Frillish", "Basculin", "Corsola", "Shellder", "Luvdisc", "Tangela"],
    "Icirrus City": ["Tympole", "Shelmet", "Karrablast", "Stunfisk", "Croagunk", "Barboach"],
    "Liberty Island": ["Victini"],
    "Lostlorn Forest": ["Sewaddle", "Cottonee", "Petilil", "Pinsir", "Heracross", "Pidove", "Venipede", "Budew", "Combee", "Audino", "Pansage", "Pansear", "Panpour", "Emolga", "Basculin", "Buizel", "Goldeen", "Poliwag", "Zorua"],
    "Marvelous Bridge": ["Ducklett", "Magikarp", "Cresselia"],
    "Mistralton Cave": ["Roggenrola", "Woobat", "Axew", "Aron", "Drilbur", "Cobalion"],
    "Moor of Icirrus": ["Tympole", "Shelmet", "Karrablast", "Stunfisk", "Croagunk", "Barboach"],
    "N's Castle": ["Reshiram", "Zekrom"],
    "Nacrene City": ["Omanyte", "Kabuto", "Aerodactyl", "Lileep", "Anorith", "Cranidos", "Shieldon", "Tirtouga", "Archen", "Cottonee", "Petilil", "Uxie"],
    "Nature Preserve": ["Seedot", "Swablu", "Girafarig", "Psyduck", "Hoothoot", "Axew", "Kecleon", "Audino", "Dunsparce", "Basculin", "Buizel", "Magikarp"],
    "Nature Sanctuary": ["Seedot", "Kecleon", "Psyduck", "Hoothoot", "Girafarig", "Swablu", "Axew", "Audino", "Dunsparce", "Buizel", "Basculin", "Magikarp"],
    "Nuvema Town": ["Snivy", "Tepig", "Oshawott"],
    "P2 Laboratory": ["Patrat", "Lillipup", "Scraggy", "Klink", "Magnemite", "Koffing", "Audino", "Frillish", "Alomomola", "Horsea", "Finneon", "Qwilfish"],
    "Pinwheel Forest": ["Sewaddle", "Cottonee", "Petilil", "Pidove", "Venipede", "Slakoth", "Audino", "Pansage", "Pansear", "Panpour", "Basculin", "Azurill", "Goldeen", "Tympole", "Timburr", "Throh", "Sawk", "Yanma", "Croagunk", "Virizion"],
    "Relic Castle": ["Sandile", "Yamask", "Sandshrew", "Baltoy", "Onix", "Larvesta"],
    "Relic Passage": ["Roggenrola", "Woobat", "Onix", "Timburr", "Drilbur", "Rattata", "Azurill", "Basculin", "Poliwag"],
    "Reversal Mountain": ["Roggenrola", "Woobat", "Numel", "Spoink", "Skorupi", "Drilbur", "Skarmory", "Trapinch", "Drifloon", "Audino", "Heatran"],
    "Roaming Unova": ["Tornadus", "Thundurus"],
    "Seaside Cave": ["Psyduck", "Woobat", "Tynamo", "Seel", "Roggenrola", "Drilbur", "Frillish", "Shellder", "Luvdisc", "Shuckle"],
    "Strange House": ["Litwick", "Gothita", "Solosis", "Rattata", "Zubat", "Shuppet"],
    "Striaton City": ["Basculin", "Corphish", "Goldeen"],
    "Twist Mountain": ["Roggenrola", "Timburr", "Cubchoo", "Cryogonal", "Onix", "Heatmor", "Woobat", "Durant", "Drilbur", "Regigigas"],
    "Undella Bay": ["Wingull", "Spheal", "Mantyke", "Frillish", "Remoraid", "Wailmer", "Shellder", "Chinchou", "Luvdisc"],
    "Undella Town": ["Wingull", "Mantyke", "Staryu", "Frillish", "Basculin", "Corsola", "Wailmer", "Shellder", "Remoraid", "Luvdisc", "Munchlax"],
    "Underground Ruins": ["Roggenrola", "Onix", "Nosepass", "Aron", "Woobat", "Durant", "Drilbur", "Regice", "Registeel", "Regirock"],
    "Victory Road": ["Durant", "Shuppet", "Golett", "Roggenrola", "Woobat", "Mienfoo", "Deino", "Drilbur", "Basculin", "Azurill", "Poliwag", "Onix", "Timburr", "Throh", "Sawk", "Audino", "Budew", "Cottonee", "Petilil", "Dunsparce", "Druddigon", "Rufflet", "Vullaby", "Heatmor", "Axew", "Pidove", "Swablu", "Buizel", "Terrakion"],
    "Village Bridge": ["Psyduck", "Bidoof", "Azurill", "Zangoose", "Seviper", "Rufflet", "Vullaby", "Audino", "Emolga", "Dunsparce", "Basculin", "Lapras", "Carvanha"],
    "Virbank City": ["Frillish", "Alomomola", "Krabby", "Finneon", "Qwilfish"],
    "Virbank Complex": ["Magnemite", "Elekid", "Magby", "Koffing", "Growlithe", "Patrat", "Audino", "Pidove", "Frillish", "Alomomola", "Krabby", "Finneon", "Qwilfish"],
    "Wellspring Cave": ["Roggenrola", "Woobat", "Drilbur", "Basculin", "Poliwag"],
    "White Forest": ["Pidgey", "Nidoran M", "Nidoran F", "Oddish", "Bellsprout", "Abra", "Machop", "Magnemite", "Gastly", "Rhyhorn", "Porygon", "Togepi", "Mareep", "Hoppip", "Elekid", "Magby", "Wurmple", "Seedot", "Ralts", "Slakoth", "Whismur", "Azurill", "Aron", "Trapinch", "Bagon", "Starly", "Shinx", "Budew", "Happiny", "Wooper", "Lotad", "Surskit", "Corphish"]
}

Kalos = {
    "Route 2": ["Bunnelby", "Fletchling", "Caterpie", "Weedle", "Pidgey", "Zigzagoon", "Scatterbug"],
    "Route 3": ["Bidoof", "Bunnelby", "Fletchling", "Pidgey", "Pichu", "Dunsparce", "Azurill", "Burmy", "Surskit", "Magikarp", "Corphish", "Goldeen"],
    "Route 4": ["Ledyba", "Flabébé", "Ralts", "Skitty", "Budew", "Combee"],
    "Route 5": ["Bunnelby", "Furfrou", "Abra", "Doduo", "Plusle", "Minun", "Gulpin", "Skiddo", "Pancham", "Scraggy"],
    "Route 6": ["Audino", "Venipede", "Oddish", "Sentret", "Kecleon", "Nincada", "Espurr", "Honedge"],
    "Route 7": ["Croagunk", "Smeargle", "Budew", "Ducklett", "Flabébé", "Volbeat", "Illumise", "Spritzee", "Swirlix", "Psyduck", "Hoppip", "Ledyba", "Burmy", "Combee", "Scatterbug", "Munchlax"],
    "Route 8": ["Spoink", "Drifloon", "Zangoose", "Seviper", "Bagon", "Mienfoo", "Absol", "Inkay", "Taillow", "Wingull", "Tentacool", "Wailmer", "Qwilfish", "Shellder", "Staryu", "Skrelp", "Clauncher", "Luvdisc", "Dwebble", "Binacle"],
    "Route 9": ["Hippopotas", "Sandile", "Helioptile"],
    "Route 10": ["Sigilyph", "Golett", "Eevee", "Snubbull", "Houndour", "Electrike", "Emolga", "Hawlucha", "Yanma", "Nosepass"],
    "Route 11": ["Makuhita", "Starly", "Throh", "Sawk", "Nidoran M", "Nidoran F", "Chingling", "Stunky", "Dedenne"],
    "Route 12": ["Slowpoke", "Chatot", "Exeggcute", "Pinsir", "Heracross", "Tauros", "Miltank", "Pachirisu", "Mareep", "Wingull", "Tentacool", "Lapras", "Mantyke", "Corsola", "Clamperl", "Remoraid", "Luvdisc", "Dwebble", "Binacle"],
    "Route 13": ["Diglett", "Trapinch", "Gible", "Geodude", "Slugma"],
    "Route 14": ["Bellsprout", "Skorupi", "Gastly", "Karrablast", "Shelmet", "Wooper", "Carnivine", "Goomy", "Ekans", "Stunfisk", "Poliwag", "Barboach"],
    "Route 15": ["Poochyena", "Purrloin", "Skorupi", "Patrat", "Foongus", "Pawniard", "Klefki", "Murkrow", "Lotad", "Buizel", "Poliwag", "Basculin"],
    "Route 16": ["Bellsprout", "Buizel", "Skorupi", "Phantump", "Foongus", "Klefki", "Murkrow", "Pumpkaboo", "Lotad", "Poliwag", "Basculin"],
    "Route 17": ["Delibird", "Snover", "Sneasel"],
    "Route 18": ["Torkoal", "Timburr", "Larvitar", "Aron", "Heatmor", "Durant", "Sandshrew", "Geodude", "Shuckle"],
    "Route 19": ["Bellsprout", "Skorupi", "Gastly", "Wooper", "Carnivine", "Karrablast", "Shelmet", "Goomy", "Ekans", "Gligar", "Stunfisk", "Poliwag", "Barboach"],
    "Route 20": ["Igglybuff", "Hoothoot", "Gothita", "Zorua", "Foongus", "Phantump", "Bonsly"],
    "Route 21": ["Swablu", "Buizel", "Teddiursa", "Scyther", "Spinda", "Lotad", "Poliwag", "Dratini", "Basculin"],
    "Route 22": ["Bunnelby", "Litleo", "Dunsparce", "Azurill", "Riolu", "Psyduck", "Farfetch'd", "Bidoof", "Magikarp", "Carvanha", "Goldeen"],
    "Ambrette Town": ["Tentacool", "Wailmer", "Relicanth", "Horsea", "Skrelp", "Clauncher", "Luvdisc", "Dwebble", "Binacle", "Omanyte", "Kabuto", "Aerodactyl", "Lileep", "Anorith", "Cranidos", "Shieldon", "Tirtouga", "Archen", "Tyrunt", "Amaura", "Magikarp", "Eevee"],
    "Aquacorde Town": ["Chespin", "Fennekin", "Froakie"],
    "Azure Bay": ["Slowpoke", "Chatot", "Exeggcute", "Inkay", "Wingull", "Tentacool", "Lapras", "Mantyke", "Alomomola", "Chinchou", "Remoraid", "Luvdisc", "Dwebble", "Binacle"],
    "Camphrier Town": ["Magikarp", "Eevee"],
    "Connecting Cave": ["Whismur", "Meditite", "Zubat", "Axew"],
    "Coumarine City": ["Magikarp", "Eevee"],
    "Couriway Town": ["Lotad", "Buizel", "Poliwag", "Basculin", "Magikarp", "Eevee"],
    "Cyllage City": ["Tentacool", "Wailmer", "Relicanth", "Horsea", "Skrelp", "Clauncher", "Luvdisc", "Onix", "Dwebble", "Binacle", "Magikarp", "Eevee"],
    "Frost Cavern": ["Swinub", "Cubchoo", "Bergmite", "Cryogonal", "Gastly", "Smoochum", "Vanillite", "Poliwag", "Buizel", "Basculin"],
    "Geosenge Town": ["Magikarp", "Eevee"],
    "Glittering Cave": ["Woobat", "Ferroseed", "Onix", "Dwebble", "Machop", "Rhyhorn", "Kangaskhan", "Mawile", "Solrock", "Lunatone", "Cubone"],
    "Laverre City": ["Magikarp", "Eevee"],
    "Lost Hotel": ["Magnemite", "Litwick", "Pawniard", "Voltorb", "Klefki", "Trubbish", "Rotom"],
    "Lumiose City": ["Ralts", "Bulbasaur", "Charmander", "Squirtle"],
    "Parfum Palace": ["Magikarp", "Corphish", "Goldeen"],
    "Pokémon Village": ["Igglybuff", "Hoothoot", "Gothita", "Ditto", "Zorua", "Foongus", "Lotad", "Poliwag", "Shuppet", "Trubbish", "Basculin"],
    "Reflection Cave": ["Mime Jr.", "Roggenrola", "Solosis", "Wynaut", "Sableye", "Carbink", "Chingling", "Woobat", "Ferroseed"],
    "Roaming Kalos": ["Articuno", "Zapdos", "Moltres"],
    "Santalune City": ["Farfetch'd"],
    "Santalune Forest": ["Caterpie", "Weedle", "Scatterbug", "Pichu", "Pansage", "Pansear", "Panpour", "Fletchling"],
    "Sea Spirit's Den": ["Articuno", "Zapdos", "Moltres"],
    "Shalour City": ["Tentacool", "Mantyke", "Alomomola", "Chinchou", "Remoraid", "Luvdisc"],
    "Snowbelle City": ["Pawniard"],
    "Team Flare HQ": ["Xerneas", "Yveltal"],
    "Terminus Cave": ["Sandshrew", "Larvitar", "Aron", "Durant", "Geodude", "Noibat", "Spinarak", "Shuckle", "Zygarde"],
    "Tower of Mastery": ["Riolu"],
    "Unknown Dungeon": ["Mewtwo"],
    "Vaniville Town": ["Chespin", "Fennekin", "Froakie"],
    "Victory Road": ["Timburr", "Druddigon", "Deino", "Geodude", "Gastly", "Lickitung", "Buizel", "Spinarak", "Noibat", "Poliwag", "Basculin", "Spearow", "Skarmory", "Lotad"]
}

Alola = {
    "Route 1": ["Pikipek", "Yungoos", "Rattata (A)", "Caterpie", "Ledyba", "Spinarak", "Grubbin", "Buneary", "Pichu", "Happiny", "Magnemite", "Wingull", "Meowth (A)", "Inkay", "Slowpoke", "Grimer (A)", "Tentacool", "Finneon", "Bonsly", "Rattata", "Rockruff", "Munchlax", "Zorua", "Gastly", "Drifloon", "Rowlet", "Litten", "Popplio"],
    "Route 2": ["Chikorita", "Bulbasaur", "Machop", "Hawlucha", "Spearow", "Growlithe", "Cutiefly", "Ekans", "Drowzee", "Makuhita", "Smeargle", "Yungoos", "Rattata (A)", "Dunsparce", "Meowth (A)", "Abra", "Furfrou", "Crabrawler"],
    "Route 3": ["Cyndaquil", "Charmander", "Spearow", "Mankey", "Cutiefly", "Delibird", "Yungoos", "Rattata (A)", "Hawlucha", "Rufflet", "Vullaby", "Bagon", "Crabrawler"],
    "Route 4": ["Lillipup", "Pikipek", "Mudbray", "Igglybuff", "Yungoos", "Grubbin", "Rattata (A)", "Eevee", "Venipede", "Weedle", "Happiny", "Crabrawler"],
    "Route 5": ["Lillipup", "Pikipek", "Fomantis", "Grubbin", "Caterpie", "Bellsprout", "Treecko", "Bounsweet", "Noibat", "Crabrawler"],
    "Route 6": ["Lillipup", "Pikipek", "Mudbray", "Igglybuff", "Yungoos", "Grubbin", "Rattata (A)", "Eevee", "Gothita", "Ralts", "Happiny", "Oricorio"],
    "Route 7": ["Spheal", "Diglett (A)", "Tentacool", "Finneon", "Wingull", "Pyukumuku", "Magikarp", "Wishiwashi", "Staryu"],
    "Route 8": ["Pikipek", "Yungoos", "Rattata (A)", "Salandit", "Fletchling", "Stufful", "Shinx", "Torchic", "Magikarp", "Wishiwashi", "Remoraid", "Chinchou", "Wimpod", "Ekans", "Crabrawler", "Cranidos", "Shieldon", "Tirtouga", "Archen", "Omanyte", "Kabuto", "Lileep", "Anorith", "Tyrunt", "Amaura"],
    "Route 9": ["Luvdisc", "Magikarp", "Corsola", "Wishiwashi", "Mareanie", "Ditto"],
    "Route 10": ["Spearow", "Yungoos", "Rattata (A)", "Ledyba", "Spinarak", "Skarmory", "Pancham", "Starly", "Pidgey", "Pineco", "Crabrawler"],
    "Route 11": ["Komala", "Ledyba", "Spinarak", "Pancham", "Pikipek", "Yungoos", "Rattata (A)", "Paras", "Morelull", "Slakoth", "Chimchar"],
    "Route 12": ["Geodude (A)", "Mudbray", "Torkoal", "Houndour", "Electrike", "Elekid", "Happiny", "Crabrawler"],
    "Route 13": ["Magikarp", "Wishiwashi", "Bruxish"],
    "Route 14": ["Wingull", "Yungoos", "Rattata (A)", "Snorunt", "Absol", "Vulpix (A)", "Sandshrew (A)", "Tentacool", "Finneon", "Frillish", "Magikarp", "Wishiwashi", "Bruxish"],
    "Route 15": ["Wingull", "Yungoos", "Rattata (A)", "Slowpoke", "Tentacool", "Finneon", "Magikarp", "Wishiwashi", "Clamperl", "Bruxish", "Sandygast", "Crabrawler", "Porygon"],
    "Route 16": ["Wingull", "Yungoos", "Rattata (A)", "Slowpoke", "Solosis", "Piplup", "Zygarde", "Crabrawler", "Scraggy"],
    "Route 17": ["Spearow", "Yungoos", "Rattata (A)", "Geodude (A)", "Scraggy", "Skarmory", "Pancham", "Pawniard", "Castform", "Goomy", "Ledyba", "Spinarak", "Crabrawler", "Kartana"],
    "Aether Paradise": ["Type: Null"],
    "Akala Outskirts": ["Wingull", "Yungoos", "Rattata (A)", "Natu", "Nosepass", "Stufful", "Honedge", "Magikarp", "Wishiwashi", "Chinchou"],
    "Altar of the Moone": ["Lunala"],
    "Altar of the Sunne": ["Solgaleo"],
    "Ancient Poni Path": ["Wingull", "Yungoos", "Rattata (A)", "Snubbull", "Furfrou", "Inkay", "Exeggcute", "Shellos", "Tepig", "Fennekin", "Tentacool", "Finneon", "Lapras", "Magikarp", "Wailmer", "Carvanha", "Relicanth", "Type: Null"],
    "Berry Fields": ["Crabrawler"],
    "Blush Mountain": ["Geodude (A)", "Torkoal", "Mudbray", "Elekid", "Grubbin", "Turtonator", "Togedemaru", "Dedenne", "Rhyhorn", "Happiny"],
    "Brooklet Hill": ["Azurill", "Mudkip", "Psyduck", "Paras", "Lillipup", "Morelull", "Poliwag", "Wingull", "Surskit", "Dewpider", "Magikarp", "Goldeen", "Basculin", "Feebas", "Tentacool", "Finneon", "Wishiwashi", "Alomomola"],
    "Diglett's Tunnel": ["Zubat", "Diglett (A)", "Larvitar", "Nihilego"],
    "Dividing Peak Tunnel": ["Kecleon", "Wimpod"],
    "Exeggutor Island": ["Exeggcute", "Wingull", "Tropius", "Shellos", "Pinsir", "Snivy", "Chespin", "Castform", "Goomy"],
    "Haina Desert": ["Sandile", "Diglett (A)", "Trapinch", "Castform", "Gible", "Baltoy", "Golett", "Celesteela"],
    "Hano Beach": ["Staryu", "Sandygast", "Tentacool", "Finneon", "Pyukumuku", "Wingull"],
    "Hau'oli Cemetery": ["Gastly", "Murkrow", "Misdreavus", "Drifloon", "Zubat", "Litwick"],
    "Hau'oli City": ["Klink", "Scatterbug", "Abra", "Furfrou", "Wingull", "Yungoos", "Rattata (A)", "Mime Jr.", "Magnemite", "Meowth (A)", "Grimer (A)", "Pichu", "Happiny", "Drowzee", "Stufful", "Tentacool", "Finneon", "Mantyke", "Remoraid", "Magikarp", "Luvdisc", "Wishiwashi", "Corsola", "Clamperl", "Mareanie"],
    "Heahea Beach": ["Rattata (A)", "Cubone (A)", "Yungoos", "Grubbin", "Cutiefly", "Dewpider", "Fomantis", "Salandit", "Togedemaru", "Mimikyu", "Jangmo-o"],
    "Heahea City": ["Pichu"],
    "Iki Town": ["Rowlet", "Litten", "Popplio"],
    "Kala'e Bay": ["Wingull", "Yungoos", "Rattata (A)", "Slowpoke", "Bagon", "Horsea", "Tentacool", "Finneon", "Mantyke", "Remoraid", "Magikarp", "Wishiwashi", "Shellder"],
    "Konikoni City": ["Ditto", "Poliwag"],
    "Lake of the Moone": ["Cosmog"],
    "Lake of the Sunne": ["Cosmog"],
    "Lush Jungle": ["Zubat", "Diglett (A)", "Salandit", "Larvesta", "Paras", "Fomantis", "Morelull", "Pikipek", "Hoothoot", "Pinsir", "Caterpie", "Bonsly", "Bounsweet", "Comfey", "Oranguru", "Passimian", "Castform", "Goomy", "Happiny", "Xurkitree"],
    "Mahalo Trail": ["Solgaleo", "Lunala"],
    "Malie City": ["Trubbish", "Grimer (A)", "Magnemite", "Yungoos", "Rattata (A)", "Minccino", "Happiny"],
    "Malie Garden": ["Poliwag", "Ledyba", "Spinarak", "Surskit", "Dewpider", "Meowth (A)", "Psyduck", "Cottonee", "Petilil", "Castform", "Magikarp", "Goldeen", "Basculin", "Celesteela", "Kartana"],
    "Melemele Meadow": ["Cottonee", "Petilil", "Cutiefly", "Oricorio", "Flabébé", "Caterpie", "Buzzwole"],
    "Melemele Sea": ["Tentacool", "Finneon", "Wingull", "Mantyke", "Remoraid", "Magikarp", "Luvdisc", "Wishiwashi", "Clamperl", "Corsola", "Mareanie"],
    "Memorial Hill": ["Gastly", "Phantump", "Zubat", "Xurkitree"],
    "Mount Hokulani": ["Spearow", "Minior", "Ditto", "Cleffa", "Skarmory", "Beldum", "Axew", "Elgyem", "Happiny", "Elekid"],
    "Mount Lanakila": ["Snorunt", "Vulpix (A)", "Sandshrew (A)", "Absol", "Yungoos", "Rattata (A)", "Castform", "Vanillite", "Zubat", "Sneasel", "Drampa", "Necrozma"],
    "Paniola Ranch": ["Mudbray", "Lillipup", "Mareep", "Tauros", "Miltank", "Eevee"],
    "Paniola Town": ["Magikarp", "Barboach"],
    "Poké Pelago": ["Scyther", "Lapras", "Emolga", "Snubbull", "Tropius", "Litleo", "Spearow", "Zubat", "Poliwag", "Magnemite", "Shellder", "Gastly", "Staryu", "Pinsir", "Skarmory", "Wingull", "Fletchling", "Carbink", "Klefki", "Pikipek", "Pyukumuku", "Slowpoke", "Seel", "Hoothoot", "Natu", "Corsola", "Hawlucha", "Cutiefly", "Comfey", "Abra", "Murkrow", "Beldum", "Drifloon", "Rufflet", "Vullaby", "Phantump", "Mime Jr.", "Smoochum", "Mareep", "Misdreavus", "Houndour", "Electrike", "Shuppet"],
    "Poni Breaker Coast": ["Tentacool", "Finneon", "Wingull", "Shellos", "Lapras", "Wailmer", "Skrelp", "Clauncher", "Magikarp", "Carvanha", "Relicanth", "Wimpod"],
    "Poni Coast": ["Diglett (A)"],
    "Poni Gauntlet": ["Wingull", "Yungoos", "Rattata (A)", "Snubbull", "Lickitung", "Psyduck", "Inkay", "Stufful", "Togepi", "Rotom", "Magikarp", "Barboach", "Dratini", "Fletchling", "Tauros"],
    "Poni Grove": ["Pikipek", "Yungoos", "Rattata (A)", "Buneary", "Snubbull", "Zorua", "Pinsir", "Riolu", "Heracross", "Tynamo", "Happiny", "Stakataka", "Blacephalon"],
    "Poni Meadow": ["Cottonee", "Petilil", "Cutiefly", "Oricorio", "Flabébé", "Misdreavus", "Sewaddle", "Magikarp", "Barboach", "Dratini"],
    "Poni Plains": ["Pikipek", "Yungoos", "Rattata (A)", "Cottonee", "Petilil", "Tauros", "Miltank", "Timburr", "Aron", "Scyther", "Makuhita", "Litleo", "Happiny", "Wingull", "Drowzee", "Rufflet", "Vullaby", "Mudbray", "Spearow", "Emolga", "Aipom", "Mankey", "Crabrawler"],
    "Poni Wilds": ["Wingull", "Yungoos", "Rattata (A)", "Snubbull", "Furfrou", "Inkay", "Exeggcute", "Shellos", "Oshawott", "Froakie", "Tentacool", "Finneon", "Lapras", "Wailmer", "Magikarp", "Relicanth", "Wimpod", "Crabrawler"],
    "Resolution Cave": ["Zubat", "Diglett (A)", "Druddigon", "Noibat", "Guzzlord"],
    "Royal Avenue": ["Barboach"],
    "Ruins of Abundance": ["Tapu Bulu"],
    "Ruins of Conflict": ["Tapu Koko"],
    "Ruins of Hope": ["Tapu Fini"],
    "Ruins of Life": ["Tapu Lele"],
    "Sandy Cave": ["Zubat", "Psyduck"],
    "Seafolk Village": ["Magikarp", "Wailmer", "Dhelmise", "Bounsweet", "Shellos", "Aerodactyl"],
    "Seaward Cave": ["Zubat", "Diglett (A)", "Psyduck", "Smoochum", "Delibird", "Totodile", "Squirtle", "Happiny", "Seel", "Magikarp", "Barboach"],
    "Secluded Shore": ["Tentacool", "Finneon", "Wingull", "Magikarp", "Wishiwashi", "Bruxish"],
    "Tapu Village": ["Wingull", "Yungoos", "Rattata (A)", "Snorunt", "Absol", "Vulpix (A)", "Sandshrew (A)", "Swinub", "Castform", "Vanillite", "Magikarp", "Wishiwashi", "Bruxish", "Geodude", "Phantump"],
    "Team Rocket's Castle": ["Voltorb"],
    "Ten Carat Hill": ["Machop", "Spinda", "Roggenrola", "Carbink", "Rockruff", "Zubat", "Mawile", "Sableye", "Diglett (A)", "Psyduck", "Deino", "Onix", "Necrozma"],
    "Thrifty Megamart": ["Zubat", "Gastly", "Shuppet", "Klefki", "Mimikyu"],
    "Ula'ula Beach": ["Crabrawler"],
    "Ula'ula Meadow": ["Cottonee", "Petilil", "Cutiefly", "Ledyba", "Spinarak", "Oricorio", "Flabébé", "Budew", "Turtwig"],
    "Ultra Megalopolis": ["Poipole"],
    "Ultra Space": ["Nihilego", "Pheromosa", "Buzzwole", "Celesteela", "Kartana", "Xurkitree", "Guzzlord"],
    "Ultra Space Wilds": ["Slugma", "Meditite", "Hippopotas", "Snover", "Dwebble", "Taillow", "Swablu", "Yanma", "Sigilyph", "Ducklett", "Seedot", "Spoink", "Skorupi", "Audino", "Helioptile", "Wooper", "Lotad", "Buizel", "Stunfisk", "Binacle", "Regirock", "Regice", "Registeel", "Groudon", "Palkia", "Heatran", "Regigigas", "Giratina", "Articuno", "Zapdos", "Moltres", "Tornadus", "Thundurus", "Landorus", "Ho-oh", "Rayquaza", "Cresselia", "Yveltal", "Mewtwo", "Raikou", "Entei", "Dialga", "Cobalion", "Terrakion", "Virizion", "Reshiram", "Zekrom", "Xerneas", "Suicune", "Lugia", "Kyogre", "Latias", "Latios", "Uxie", "Mesprit", "Azelf", "Kyurem"],
    "Vast Poni Canyon": ["Zubat", "Roggenrola", "Carbink", "Diglett (A)", "Sableye", "Psyduck", "Magikarp", "Barboach", "Basculin", "Corphish", "Dratini", "Machop", "Rockruff", "Mienfoo", "Murkrow", "Skarmory", "Jangmo-o"],
    "Verdant Cavern": ["Zubat", "Diglett (A)", "Noibat", "Rattata (A)", "Yungoos", "Pheromosa"],
    "Wela Volcano Park": ["Fletchling", "Salandit", "Cubone", "Magby", "Kangaskhan", "Happiny", "Nihilego"]
}

Galar = {
    "Route 1": ["Skwovet", "Blipbug", "Caterpie", "Grubbin", "Hoothoot", "Rookidee", "Wooloo", "Nickit"],
    "Route 2": ["Blipbug", "Rookidee", "Lotad", "Seedot", "Purrloin", "Hoothoot", "Arrokuda", "Magikarp", "Chewtle", "Skwovet", "Nickit", "Yamper", "Zigzagoon(G)", "Gossifleur", "Feebas"],
    "Route 3": ["Rookidee", "Machop", "Pancham", "Mudbray", "Klink", "Sizzlipede", "Skwovet", "Cherubi", "Zigzagoon (G)", "Gossifleur", "Vulpix", "Growlithe", "Trubbish", "Stunky", "Tyrogue", "Rolycoly"],
    "Route 4": ["Meowth (G)", "Wooloo", "Milcery", "Joltik", "Cutiefly", "Budew", "Ferroseed", "Magikarp", "Chewtle", "Goldeen", "Skwovet", "Electrike", "Yamper", "Pumpkaboo", "Pichu", "Eevee"],
    "Route 5": ["Blipbug", "Lotad", "Seedot", "Espurr", "Spritzee", "Swirlix", "Applin", "Nincada", "Dewpider", "Magikarp", "Chewtle", "Goldeen", "Skwovet", "Stufful", "Minccino", "Wynaut", "Drifloon", "Farfetch'd (G)"],
    "Route 6": ["Silicobra", "Heatmor", "Durant", "Duskull", "Hippopotas", "Skorupi", "Torkoal", "Hawlucha", "Magikarp", "Chewtle", "Goldeen", "Skwovet", "Yamask (G)", "Helioptile", "Diglett", "Maractus", "Trapinch", "Axew"],
    "Route 7": ["Toxel", "Karrablast", "Shelmet", "Rookidee", "Purrrloin", "Tympole", "Espurr", "Skwovet", "Meowth (G)", "Joltik", "Nickit", "Inkay", "Morpeko"],
    "Route 8": ["Silicobra", "Rhyhorn", "Duskull", "Gastly", "Bronzor", "Hippopotas", "Skorupi", "Falinks", "Roggenrola", "Timburr", "Golett", "Pawniard", "Rufflet", "Vullaby", "Solrock", "Lunatone", "Togedemaru", "Snom", "Sneasel", "Snover", "Delibird", "Darumaka (G)", "Snorunt", "Vanillite", "Throh", "Sawk"],
    "Route 9": ["Cramorant", "Remoraid", "Krabby", "Pincurchin", "Wingull", "Qwilfish", "Mantyke", "Frillish", "Wishiwashi", "Pyukumuku", "Mareanie", "Shellos", "Inkay", "Wailmer", "Lapras", "Skwovet", "Clobbopus", "Binacle", "Bergmite", "Dhelmise", "Meowth (G)", "Nickit", "Purrloin", "Morpeko"],
    "Route 10": ["Vanillite", "Snover", "Cubchoo", "Snom", "Darumaka (G)", "Stonjourner", "Eiscue", "Mr. Mime (G)", "Sneasel", "Duraludon", "Klink", "Rhyhorn"],
    "Axew's Eye": ["Klink", "Snover", "Delibird", "Bunnelby", "Pidove", "Stufful", "Bounsweet", "Budew", "Oddish", "Munna", "Purrloin", "Wingull", "Grubbin", "Baltoy", "Dwebble", "Mudbray", "Vanillite", "Vulpix", "Growlithe", "Corphish", "Electrike", "Magikarp", "Remoraid", "Wishiwashi", "Skwovet", "Cherubi", "Bronzor", "Krabby", "Axew", "Machop", "Drifloon", "Tympole"],
    "Ballimere Lake": ["Mime Jr.", "Cottonee", "Skwovet", "Gossifleur", "Yamper", "Munchlax", "Hatenna", "Dewpider", "Magby", "Elekid", "Basculin", "Magikarp", "Barboach", "Anorith", "Dratini", "Relicanth", "Vanillite", "Shuckle", "Tyrunt", "Rookidee", "Eevee", "Indeedee", "Audino", "Swablu", "Zigzagoon (G)", "Noibat", "Morpeko", "Mimikyu", "Cryogonal", "Rolycoly", "Joltik"],
    "Brawler's Cave": ["Poliwag", "Barboach", "Whismur", "Psyduck", "Woobat", "Lickitung", "Azurill", "Happiny"],
    "Bridge Field": ["Sneasel", "Cubchoo", "Inkay", "Mawile", "Tympole", "Vanillite", "Ferroseed", "Nickit", "Wynaut", "Purrloin", "Togepi", "Karrablast", "Shelmet", "Milcery", "Litwick", "Elgyem", "Binacle", "Shellos", "Wimpod", "Rhyhorn", "Rufflet", "Vullaby", "Bonsly", "Rolycoly", "Noibat", "Qwilfish", "Goldeen", "Magikarp", "Chewtle", "Chinchou", "Skwovet", "Cherubi", "Cufant", "Zigzagoon (G)", "Cutiefly", "Toxel", "Croagunk", "Scraggy", "Throh", "Sawk", "Munna", "Stufful", "Bronzor", "Cramorant", "Baltoy", "Maractus", "Frillish", "Pidove", "Woobat"],
    "Challenge Beach": ["Igglybuff", "Buneary", "Blipbug", "Happiny", "Inkay", "Shinx", "Fomantis", "Magikarp", "Wishiwashi", "Dhelmise", "Skwovet", "Applin", "Magnemite", "Psyduck", "Dedenne", "Morpeko", "Tentacool", "Wingull", "Drifloon", "Corphish", "Arrokuda", "Cramorant", "Staryu"],
    "Challenge Road": ["Roggenrola", "Mienfoo", "Blipbug", "Happiny", "Pawniard", "Shinx", "Silicobra", "Fletchling", "Salandit", "Skarmory", "Rockruff", "Jangmo-o", "Scraggy"],
    "Courageous Cavern": ["Chewtle", "Tentacool", "Clobbopus", "Magikarp", "Shellder", "Woobat", "Wimpod", "Dwebble", "Pincurchin", "Happiny"],
    "Crown Shrine": ["Glastrier", "Spectrier", "Calyrex"],
    "Dappled Grove": ["Snorunt", "Vanillite", "Klink", "Bunnelby", "Lotad", "Seedot", "Budew", "Bounsweet", "Stufful", "Stunky", "Ralts", "Purrloin", "Tympole", "Grubbin", "Baltoy", "Golett", "Snover", "Vulpix", "Growlithe", "Mudbray", "Joltik", "Skwovet", "Cherubi", "Delibird", "Oddish", "Hoothoot", "Tyrogue", "Electrike"],
    "Dusty Bowl": ["Bronzor", "Klink", "Hatenna", "Ferroseed", "Gossifleur", "Wooloo", "Applin", "Stunky", "Budew", "Espurr", "Ralts", "Wingull", "Binacle", "Diglett", "Bonsly", "Swinub", "Snover", "Rookidee", "Timburr", "Rhyhorn", "Stunfisk (G)", "Mudbray", "Rolycoly", "Chewtle", "Yamper", "Grubbin", "Arrokuda", "Chinchou", "Qwilfish", "Magikarp", "Mawile", "Cubchoo", "Nickit", "Koffing", "Croagunk", "Scraggy", "Tyroague", "Wynaut", "Sableye", "Duskull", "Gothita", "Solosis", "Electrike", "Tympole", "Hippopotas", "Drilbur", "Shuckle", "Sneasel", "Vanillite", "Delibird", "Vulpix", "Growlithe", "Rufflet", "Vullaby", "Togepi"],
    "East Lake Axewell": ["Vanillite", "Snover", "Minccino", "Stufful", "Oddish", "Bunnelby", "Pidove", "Budew", "Purrloin", "Munna", "Wingull", "Grubbin", "Dwebble", "Baltoy", "Onix", "Snorunt", "Mudbray", "Vulpix", "Growlithe", "Joltik", "Electrike", "Goldeen", "Shellder", "Frillish", "Chinchou", "Magikarp", "Wishiwashi", "Pancham", "Bounsweet", "Caterpie"],
    "Fields of Honor": ["Igglybuff", "Buneary", "Blipbug", "Happiny", "Inkay", "Ralts", "Krabby", "Fomantis", "Tentacool", "Wingull", "Mantyke", "Drifloon", "Magikarp", "Remoraid", "Skwovet", "Applin", "Abra", "Klefki", "Slowpoke (G)"],
    "Forest of Focus": ["Venipede", "Karrablast", "Foongus", "Happiny", "Pawniard", "Zorua", "Corphish", "Silicobra", "Fomantis", "Arrokuda", "Cramorant", "Goldeen", "Magikarp", "Skwovet", "Applin", "Emolga", "Tangela", "Pichu", "Oranguru", "Passimian", "Croagunk"],
    "Frigid Sea": ["Spheal", "Mime Jr.", "Vanillite", "Bergmite", "Hatenna", "Dewpider", "Elekid", "Wailmer", "Cryogonal", "Eiscue", "Tirtouga", "Lapras", "Pincurchin", "Magikarp", "Basculin", "Dhelmise", "Cubchoo", "Absol", "Audino", "Sneasel", "Swablu", "Mimikyu"],
    "Frostpoint Field": ["Smoochum", "Mime Jr.", "Snover", "Vanillite", "Wooloo", "Swablu", "Gothita", "Solosis", "Hatenna", "Magby", "Skwovet", "Cryogonal", "Amaura", "Sneasel"],
    "Galar Mine": ["Roggenrola", "Timburr", "Rolycoly", "Diglett", "Woobat", "Drilbur"],
    "Galar Mine No. 2": ["Noibat", "Wimpod", "Scraggy", "Shuckle", "Shellos", "Binacle", "Chewtle", "Stunfisk (G)", "Croagunk", "Barboach", "Corphish"],
    "Giant's Bed": ["Nidoran M", "Nidoran F", "Mime Jr.", "Vanillite", "Shelmet", "Wooloo", "Swablu", "Hatenna", "Dewpider", "Magby", "Elekid", "Magikarp", "Barboach", "Basculin", "Lileep", "Skwovet", "Bronzor", "Stonjourner", "Snorunt", "Cryogonal", "Absol", "Audino", "Timburr", "Eevee", "Zigzagoon (G)", "Litwick", "Impidimp", "Cleffa", "Mimikyu", "Heatmor", "Durant", "Joltik"],
    "Giant's Cap": ["Snorunt", "Pawniard", "Delibird", "Blipbug", "Lotad", "Seedot", "Gossifleur", "Stunky", "Munna", "Karrablast", "Shelmet", "Duskull", "Tympole", "Shellos", "Golett", "Drilbur", "Mudbray", "Snover", "Baltoy", "Diglett", "Joltik", "Toxel", "Goldeen", "Krabby", "Corphish", "Magikarp", "Skwovet", "Cherubi", "Sneasel", "Minccino", "Vanillite", "Zigzagoon (G)", "Riolu", "Hoothoot", "Purrloin", "Croagunk", "Scraggy", "Oddish", "Gothita", "Solosis", "Cleffa", "Chewtle", "Wooper", "Rolycoly", "Bunnelby", "Shuckle", "Torkoal", "Electrike", "Solrock", "Lunatone", "Rhyhorn", "Roggenrola"],
    "Giant's Foot": ["Bronzor", "Mime Jr.", "Vanillite", "Cufant", "Sizzlipede", "Phantump", "Hatenna", "Dewpider", "Magby", "Elekid", "Magikarp", "Barboach", "Basculin", "Lileep", "Skwovet", "Stonjourner", "Baltoy", "Snorunt", "Archen", "Cryogonal", "Absol", "Audino", "Timburr", "Swablu", "Impidimp", "Mimikyu", "Joltik"],
    "Giant's Mirror": ["Swinub", "Cubchoo", "Snover", "Machop", "Koffing", "Skorupi", "Blipbug", "Budew", "Impidimp", "Milcery", "Mimikyu", "Shellos", "Hippopotas", "Bunnelby", "Diglett", "Torkoal", "Joltik", "Applin", "Chewtle", "Mareanie", "Chinchou", "Magikarp", "Skwovet", "Cherubi", "Pawniard", "Vanillite", "Natu", "Woobat", "Pumpkaboo", "Oddish", "Pidove", "Nickit", "Caterpie", "Throh", "Sawk", "Farfetch'd (G)", "Corsola (G)", "Spritzee", "Swirlix", "Morelull", "Cutiefly", "Wimpod", "Tympole", "Rhyhorn", "Drilbur", "Delibird", "Heatmor", "Durant", "Helioptile", "Yamper", "Rookidee", "Roggenrola"],
    "Giant's Seat": ["Delibird", "Bronzor", "Swinub", "Stufful", "Onix", "Bunnelby", "Pidove", "Machop", "Gastly", "Natu", "Purrloin", "Wooper", "Lotad", "Seedot", "Mudbray", "Dwebble", "Electrike", "Corphish", "Shellder", "Pyukumuku", "Magikarp", "Skwovet", "Cherubi", "Snover", "Snorunt", "Tyrogue", "Duskull", "Munna", "Vulpix", "Growlithe", "Tympole"],
    "Glimwood Tangle": ["Morelull", "Impidimp", "Hatenna", "Spritzee", "Swirlix", "Phantump", "Sinistea", "Ponyta (G)", "Oranguru", "Passimian", "Indeedee"],
    "Hammerlocke Hills": ["Snorunt", "Vanillite", "Honedge", "Klink", "Inkay", "Espurr", "Rookidee", "Wooloo", "Machop", "Nickit", "Hawlucha", "Hatenna", "Impidimp", "Wingull", "Karrablast", "Shelmet", "Diglett", "Dwebble", "Drilbur", "Swinub", "Delibird", "Vulpix", "Growlithe", "Baltoy", "Toxel", "Grubbin", "Skwovet", "Cherubi", "Sneasel", "Wynaut", "Pumpkaboo", "Stufful", "Bonsly", "Morelull", "Gastly", "Tympole", "Trapinch", "Axew", "Cubchoo", "Maractus", "Wimpod", "Pidove"],
    "Honeycalm Island": ["Combee", "Petilil", "Blipbug", "Happiny", "Wingull", "Tentacool", "Wailmer", "Mantyke", "Skrelp", "Clauncher", "Frillish", "Drifloon", "Magikarp", "Fletchling", "Chinchou", "Wishiwashi"],
    "Honeycalm Sea": ["Tentacool", "Wingull", "Wailmer", "Mantyke", "Skrelp", "Clauncher", "Magikarp", "Frillish", "Drifloon", "Fletchling", "Chinchou", "Wishiwashi", "Carvanha"],
    "Hulbury": ["Arrokuda", "Chinchou", "Chewtle", "Basculin", "Wishiwashi"],
    "Insular Sea": ["Exeggcute", "Wingull", "Blipbug", "Happiny", "Tentacool", "Horsea", "Mantyke", "Skrelp", "Clauncher", "Magikarp", "Frillish", "Drifloon", "Fletchling", "Chinchou", "Wishiwashi", "Skwovet", "Applin"],
    "Lake of Outrage": ["Meowth (G)", "Honedge", "Rookidee", "Togedemaru", "Eiscue", "Duraludon", "Zigzagoon (G)", "Stufful", "Blipbug", "Ditto", "Stunky", "Impidimp", "Pancham", "Falinks", "Larvitar", "Jangmo-o", "Dreepy", "Baltoy", "Bronzor", "Indeedee", "Ralts", "Wingull", "Cramorant", "Wooper", "Deino", "Goomy", "Binacle", "Diglett", "Hippopotas", "Stunfisk (G)", "Stonjourner", "Snom", "Swinub", "Mr. Mime (G)", "Rhyhorn", "Rolycoly", "Silicobra", "Turtonator", "Yamper", "Chewtle", "Frillish", "Drampa", "Vanillite", "Mantyke", "Arrokuda", "Chinchou", "Qwilfish", "Magikarp", "Skwovet", "Cherubi", "Klink", "Pawniard", "Golett", "Ditto", "Cufant", "Elgyem", "Rufflet", "Vullaby", "Sigilyph", "Trubbish", "Skorupi", "Weezing (G)", "Hitmontop", "Wynaut", "Hatenna", "Gothita", "Solosis", "Tympole", "Dewpider", "Wimpod", "Rotom", "Drilbur", "Roggenrola", "Snorunt", "Snover", "Bergmite", "Vulpix", "Growlithe", "Heatmor", "Durant", "Litwick", "Trapinch", "Joltik", "Noibat", "Axew", "Morpeko"],
    "Lakeside Cave": ["Zubat", "Aron", "Carbink", "Rolycoly", "Sableye", "Mawile", "Ferroseed", "Noibat", "Audino"],
    "Loop lagoon": ["Wingull", "Blipbug", "Clobbopus", "Happiny", "Inkay", "Drifloon", "Krabby", "Fletchling", "Tentacool", "Magikarp", "Shellder", "Skwovet", "Applin", "Mareanie", "Dwebble", "Pincurchin", "Sandygast"],
    "Motostoke": ["Magikarp", "Chewtle", "Barboach"],
    "Motostoke Outskirts": ["Croagunk", "Scraggy", "Roggenrola", "Pawniard", "Chewtle", "Impidimp", "Hoothoot", "Bonsly", "Koffing", "Hatenna", "Throh", "Sawk", "Salandit"],
    "Motostoke Riverbank": ["Pawniard", "Sneasel", "Rookidee", "Ferroseed", "Sigilyph", "Hoothoot", "Gossifleur", "Wooloo", "Skorupi", "Espurr", "Elgyem", "Karrablast", "Shelmet", "Binacle", "Rhyhorn", "Onix", "Vanillite", "Litwick", "Shellos", "Wimpod", "Yamper", "Arrokuda", "Basculin", "Mantyke", "Mareanie", "Skwovet", "Cherubi", "Purrloin", "Cutiefly", "Munchlax", "Koffing", "Throh", "Sawk", "Cleffa", "Wynaut", "Duskull", "Chewtle", "Dewpider", "Bonsly", "Rolycoly", "Salandit", "Torkoal", "Toxel"],
    "North Lake Miloch": ["Delibird", "Snover", "Stunky", "Snorunt", "Stufful", "Pidove", "Bunnelby", "Machop", "Gastly", "Natu", "Ralts", "Tympole", "Grubbin", "Dwebble", "Baltoy", "Mudbray", "Joltik", "Vanillite", "Drifloon", "Frillish", "Barboach", "Wingull", "Goldeen", "Magikarp", "Basculin", "Skwovet", "Cherubi", "Klink", "Snorunt", "Purrloin", "Oddish", "Ralts", "Golett", "Dwebble", "Vulpix", "Growlithe"],
    "Old Cemetery": ["Vanillite", "Sinistea", "Nidoran M", "Nidoran F", "Mime Jr.", "Karrablast", "Phantump", "Hatenna", "Dewpider", "Magby", "Elekid", "Cryogonal", "Dreepy", "Absol", "Audino", "Litwick", "Ponyta (G)", "Mimikyu", "Heatmor", "Durant", "Joltik"],
    "Path to the Peak": ["Snom", "Absol", "Audino", "Druddigon", "Swablu"],
    "Potbottom Desert": ["Sandile", "Rhyhorn", "Torkoal", "Rufflet", "Vullaby", "Happiny", "Pawniard", "Jangmo-o", "Shinx", "Silicobra", "Scraggy", "Fletchling"],
    "Roaring-Sea Caves": ["Magikarp", "Omanyte", "Kabuto", "Barboach", "Basculin", "Vanillite", "Feebas", "Zubat", "Carbink", "Swinub", "Larvitar", "Deino", "Riolu", "Audino"],
    "Rolling Fields": ["Swinub", "Delibird", "Snorunt", "Bunnelby", "Minccino", "Bounsweet", "Caterpie", "Oddish", "Budew", "Munna", "Natu", "Lotad", "Seedot", "Wingull", "Dwebble", "Baltoy", "Golett", "Vanillite", "Mudbray", "Vulpix", "Growlithe", "Joltik", "Electrike", "Skwovet", "Cherubi", "Tyrogue", "Combee", "Ralts", "Pancham", "Pidove", "Diglett", "Roggenrola"],
    "Slippery Slope": ["Swinub", "Smoochum", "Mime Jr.", "Snom", "Wooloo", "Swablu", "Gothita", "Solosis", "Hatenna", "Magby", "Skwovet", "Cryogonal", "Amaura", "Audino", "Sneasel", "Phantump", "Impidimp", "Mimikyu"],
    "Slumbering Weald": ["Skwovet", "Weezing (G)", "Munna", "Rookidee", "Hoothoot", "Blipbug", "Caterpie", "Grubbin", "Stunfisk (G)", "Barboach", "Magikarp"],
    "Snowslide Slope": ["Beldum", "Mime Jr.", "Vanillite", "Snom", "Wooloo", "Phantump", "Magby", "Magikarp", "Basculin", "Snorunt", "Cubchoo", "Cryogonal", "Amaura", "Darumaka (G)", "Absol", "Audino", "Druddigon", "Sneasel", "Impidimp", "Cleffa", "Mimikyu", "Delibird"],
    "Soothing Wetlands": ["Dunsparce", "Skorupi", "Shelmet", "Happiny", "Pawniard", "Corphish", "Fomantis", "Magikarp", "Barboach", "Skwovet", "Applin", "Wooper", "Lickitung", "Bouffalant", "Croagunk", "Goomy", "Chewtle"],
    "South Lake Miloch": ["Klink", "Snover", "Corphish", "Machop", "Wingull", "Tympole", "Budew", "Tyrogue", "Natu", "Ralts", "Nincada", "Wooper", "Baltoy", "Snorunt", "Vanillite", "Vulpix", "Growlithe", "Electrike", "Joltik", "Drifloon", "Goldeen", "Barboach", "Magikarp", "Remoraid", "Pyukumuku", "Krabby", "Stunky", "Lotad", "Seedot", "Bronzor", "Mudbray", "Dwebble"],
    "Stepping-Stone Sea": ["Exeggcute", "Skwovet", "Blipbug", "Happiny", "Wingull", "Tentacool", "Frillish", "Mantyke", "Skrelp", "Clauncher", "Magikarp", "Drifloon", "Fletchling", "Chinchou", "Wishiwashi", "Applin"],
    "Stony Wilderness": ["Sneasel", "Pawniard", "Cubchoo", "Impidimp", "Roggenrola", "Timburr", "Cutiefly", "Gossifleur", "Cottonee", "Spritzee", "Swirlix", "Nickit", "Blipbug", "Togepi", "Barboach", "Shellos", "Pichu", "Rhyhorn", "Drilbur", "Shuckle", "Toxel", "Applin", "Baltoy", "Bronzor", "Golett", "Zigzagoon (G)", "Ferroseed", "Nincada", "Tyrogue", "Machop", "Croagunk", "Scraggy", "Hatenna", "Munna", "Dewpider", "Cramorant", "Bonsly", "Dwebble", "Maractus", "Salandit", "Yamper", "Rufflet", "Vullaby", "Bounsweet", "Pidove", "Sigilyph"],
    "Three-Point Pass": ["Bronzor", "Mime Jr.", "Vanillite", "Bergmite", "Wooloo", "Phantump", "Hatenna", "Dewpider", "Magby", "Elekid", "Audino", "Baltoy", "Cryogonal", "Absol", "Golett", "Swablu", "Mimikyu", "Druddigon", "Heatmor", "Durant", "Joltik"],
    "Training Lowlands": ["Lillipup", "Blipbug", "Happiny", "Inkay", "Shinx", "Silicobra", "Fomantis", "Corphish", "Arrokuda", "Cramorant", "Magikarp", "Carvanha", "Skwovet", "Applin", "Tauros", "Miltank", "Scyther", "Pinsir", "Heracross", "Staryu"],
    "Tunnel to the Top": ["Zubat", "Carbink", "Snorunt", "Bagon", "Gible", "Cleffa", "Audino"],
    "Warm-Up Tunnel": ["Sandshrew", "Cubone", "Kangaskhan", "Torkoal", "Happiny"],
    "Watchtower Ruins": ["Snover", "Snorunt", "Duskull", "Drifloon", "Golett", "Bounsweet", "Pidove", "Machop", "Gastly", "Purrloin", "Tympole", "Wingull", "Dwebble", "Vulpix", "Growlithe", "Electrike", "Grubbin", "Cherubi", "Skwovet", "Delibird", "Oddish", "Ralts", "Shuckle", "Woobat", "Noibat"],
    "West Lake Axewell": ["Klink", "Delibird", "Vanillite", "Bunnelby", "Wooper", "Krabby", "Wingull", "Bounsweet", "Pancham", "Tyrogue", "Natu", "Ralts", "Tympole", "Nincada", "Baltoy", "Mudbray", "Snorunt", "Vulpix", "Growlithe", "Electrike", "Joltik", "Magikarp", "Frillish", "Goldeen", "Remoraid", "Shellder", "Chinchou", "Wishiwashi", "Lotad", "Seedot", "Budew", "Dwebble"],
    "Workout Sea": ["Exeggcute", "Ditto", "Blipbug", "Happiny", "Mantyke", "Wingull", "Tentacool", "Skrelp", "Clauncher", "Magikarp", "Frillish", "Drifloon", "Fletchling", "Chinchou", "Remoraid", "Skwovet", "Applin"]
}